import { createClient } from 'npm:@supabase/supabase-js@2.57.4'
const url=Deno.env.get('SUPABASE_URL')||''
const pub=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}').default
const projectOrigin=(()=>{try{return new URL(url).origin}catch{return ''}})()
function allowedOrigin(origin:string|null){if(!origin)return true;if(origin==='https://karkalkan.vercel.app'||origin===projectOrigin)return true;try{const u=new URL(origin);return u.protocol==='https:'&&Boolean(Deno.env.get('KARKALKAN_VERCEL_PREVIEW_HOST_SUFFIX'))&&u.hostname.endsWith(String(Deno.env.get('KARKALKAN_VERCEL_PREVIEW_HOST_SUFFIX')))}catch{return false}}
function headers(origin:string|null){const h:Record<string,string>={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, max-age=0','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Vary':'Origin'};if(origin&&allowedOrigin(origin)){h['Access-Control-Allow-Origin']=origin;h['Access-Control-Allow-Headers']='authorization, apikey, content-type';h['Access-Control-Allow-Methods']='GET, OPTIONS'}return h}
const json=(status:number,body:unknown,origin:string|null)=>new Response(JSON.stringify(body),{status,headers:headers(origin)})
const validUuid=(v:string)=>/^[0-9a-f-]{36}$/i.test(v)
Deno.serve(async(req:Request)=>{const origin=req.headers.get('Origin');if(!allowedOrigin(origin))return json(403,{error:'ORIGIN_NOT_ALLOWED'},origin);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(origin)});if(req.method!=='GET')return json(405,{error:'METHOD_NOT_ALLOWED'},origin);const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json(401,{error:'UNAUTHORIZED'},origin);if(!url||!pub)return json(503,{error:'SERVER_CONFIG'},origin);const token=auth.slice(7),client=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),{data:userData,error:userErr}=await client.auth.getUser(token),user=userData?.user;if(userErr||!user)return json(401,{error:'UNAUTHORIZED'},origin);const u=new URL(req.url),connectionId=String(u.searchParams.get('connection_id')||''),limitRaw=Number(u.searchParams.get('limit')||10),limit=Math.min(25,Math.max(1,Number.isInteger(limitRaw)?limitRaw:10));if(!validUuid(connectionId))return json(400,{error:'INVALID_CONNECTION'},origin);const {data:connection,error:connErr}=await client.from('marketplace_connections').select('id').eq('id',connectionId).maybeSingle();if(connErr)return json(500,{error:'DB_ERROR'},origin);if(!connection)return json(404,{error:'NOT_FOUND'},origin);const {data:runs,error:runsErr}=await client.from('marketplace_sync_runs').select('id,range_start,range_end,status,imported_orders,imported_transactions,safe_error_code,result_summary,started_at,finished_at,created_at').eq('connection_id',connectionId).order('started_at',{ascending:false}).limit(limit);if(runsErr)return json(500,{error:'DB_READ_FAILED'},origin);const safe=(runs||[]).map((r:any)=>({id:r.id,rangeStart:r.range_start,rangeEnd:r.range_end,status:r.status,importedOrders:r.imported_orders,importedTransactions:r.imported_transactions,safeErrorCode:r.safe_error_code,resultSummary:r.result_summary,startedAt:r.started_at,finishedAt:r.finished_at,createdAt:r.created_at}));return json(200,{runs:safe},origin)})
