import { createClient } from 'npm:@supabase/supabase-js@2.57.4'

const PROJECT_URL=Deno.env.get('SUPABASE_URL')||''
const PROJECT_ORIGIN=(()=>{try{return new URL(PROJECT_URL).origin}catch{return ''}})()
const fmt=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'})
const PAGE=1000,MAX_ROWS=100000
function allowedOrigin(o:string|null){if(!o)return true;if(o==='https://karkalkan.vercel.app'||o===PROJECT_ORIGIN)return true;try{const u=new URL(o);return u.protocol==='https:'&&u.hostname.endsWith('-krgzabdullah22-8562s-projects.vercel.app')}catch{return false}}
function headers(o:string|null){const h:Record<string,string>={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, max-age=0','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Vary':'Origin'};if(o&&allowedOrigin(o)){h['Access-Control-Allow-Origin']=o;h['Access-Control-Allow-Headers']='authorization, apikey, content-type';h['Access-Control-Allow-Methods']='GET, OPTIONS'}return h}
function json(s:number,b:unknown,o:string|null){return new Response(JSON.stringify(b),{status:s,headers:headers(o)})}
function cents(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.round(n*100):0}
function money(v:number){return Math.round(v)/100}
function posInt(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.trunc(n)):0}
function signedInt(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.trunc(n):0}
function ratio(n:number,d:number){return d?Math.max(0,Math.min(1,n/d)):0}
function dayKey(date:Date){const p=fmt.formatToParts(date),g=(t:string)=>p.find(x=>x.type===t)?.value;return `${g('year')}-${g('month')}-${g('day')}`}
function startDay(days:number){const p=fmt.formatToParts(new Date()),g=(t:string)=>Number(p.find(x=>x.type===t)?.value),mid=Date.UTC(g('year'),g('month')-1,g('day'))-3*60*60*1000;return dayKey(new Date(mid-(days-1)*86400000))}
function rankBasis(v:Set<string>){if(v.has('mixed_fallback'))return'mixed_fallback';if(v.has('settlement_transaction_proxy'))return'settlement_transaction_proxy';if(v.has('order_v2_sales_settlement_return_proxy'))return'order_v2_sales_settlement_return_proxy';if(v.has('order_v2_sales_claims_accepted_returns'))return'order_v2_sales_claims_accepted_returns';if(v.has('order_v2_exact_sales'))return'order_v2_exact_sales';return'settlement_transaction_proxy'}
function rankSales(v:Set<string>){if(v.has('mixed_fallback'))return'mixed_fallback';if(v.has('settlement_transaction_proxy'))return'settlement_transaction_proxy';if(v.has('order_v2_quantity'))return'order_v2_quantity';return'settlement_transaction_proxy'}
function rankReturn(v:Set<string>){if(v.has('mixed_fallback'))return'mixed_fallback';if(v.has('settlement_transaction_proxy'))return'settlement_transaction_proxy';if(v.has('claims_accepted_items'))return'claims_accepted_items';return'settlement_transaction_proxy'}
async function paged(make:(from:number,to:number)=>PromiseLike<any>){const out:any[]=[];for(let from=0;from<MAX_ROWS;from+=PAGE){const {data,error}=await make(from,from+PAGE-1);if(error)throw error;const rows=Array.isArray(data)?data:[];out.push(...rows);if(rows.length<PAGE)return out}throw new Error('DATA_TOO_LARGE')}

Deno.serve(async(req:Request)=>{
 const origin=req.headers.get('Origin');if(!allowedOrigin(origin))return json(403,{error:'ORIGIN_NOT_ALLOWED'},origin);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(origin)});if(req.method!=='GET')return json(405,{error:'METHOD_NOT_ALLOWED'},origin)
 const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json(401,{error:'UNAUTHORIZED'},origin)
 const key=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}').default;if(!PROJECT_URL||!key)return json(503,{error:'SERVER_CONFIG'},origin)
 const sb=createClient(PROJECT_URL,key,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),{data:ud,error:ue}=await sb.auth.getUser(auth.slice(7));if(ue||!ud?.user)return json(401,{error:'UNAUTHORIZED'},origin)
 const u=new URL(req.url),connectionId=u.searchParams.get('connection_id')||'',raw=Number(u.searchParams.get('days')||30),days=[7,30].includes(raw)?raw:30;if(!/^[0-9a-f-]{36}$/i.test(connectionId))return json(400,{error:'INVALID_CONNECTION'},origin)
 const {data:connection,error:ce}=await sb.from('marketplace_connections').select('id,marketplace,display_name,status,last_sync_at,last_sync_status').eq('id',connectionId).maybeSingle();if(ce)return json(500,{error:'DB_ERROR'},origin);if(!connection)return json(404,{error:'NOT_FOUND'},origin);const start=startDay(days)
 let daily:any[],products:any[];try{[daily,products]=await Promise.all([
   paged((f,t)=>sb.from('marketplace_daily_financials').select('id,day,currency,gross_sales,gross_returns,commission_cost,discount_cost,coupon_cost,provision_net,manual_refund_net,platform_promo_net,delivery_fee_net,correction_net,settlement_adjustment_net,settlement_coverage,platform_service_fee_cost,cargo_cost,stoppage_net,other_financial_coverage,seller_revenue,transaction_count').eq('connection_id',connectionId).gte('day',start).order('day',{ascending:true}).range(f,t)),
   paged((f,t)=>sb.from('marketplace_product_daily_metrics').select('id,external_product_id,sku,barcode,product_name,units,sales_units,return_units,unit_basis,sales_unit_basis,return_unit_basis,order_line_matches,return_proxy_matches,claim_item_matches,gross_sales,gross_returns,commission_cost,seller_revenue,known_cogs,estimated_profit,estimated_margin,profit_confidence').eq('connection_id',connectionId).gte('day',start).order('id',{ascending:true}).range(f,t))
 ])}catch(e){return json(e instanceof Error&&e.message==='DATA_TOO_LARGE'?409:500,{error:e instanceof Error&&e.message==='DATA_TOO_LARGE'?'DATA_TOO_LARGE':'DB_ERROR'},origin)}
 const acc=daily.reduce((a:any,r:any)=>{for(const[k,c]of[['grossSales','gross_sales'],['grossReturns','gross_returns'],['commissionCost','commission_cost'],['discountCost','discount_cost'],['couponCost','coupon_cost'],['provisionNet','provision_net'],['manualRefundNet','manual_refund_net'],['platformPromoNet','platform_promo_net'],['deliveryFeeNet','delivery_fee_net'],['correctionNet','correction_net'],['settlementAdjustmentNet','settlement_adjustment_net'],['platformServiceFeeCost','platform_service_fee_cost'],['cargoCost','cargo_cost'],['stoppageNet','stoppage_net'],['sellerRevenue','seller_revenue']]as const)a[k]+=cents(r[c]);a.transactions+=posInt(r.transaction_count);if(r.settlement_coverage==='settlement_adjustments_v1')a.adjustedDays++;if(r.other_financial_coverage&&r.other_financial_coverage!=='none')a.otherFinancialDays++;return a},{grossSales:0,grossReturns:0,commissionCost:0,discountCost:0,couponCost:0,provisionNet:0,manualRefundNet:0,platformPromoNet:0,deliveryFeeNet:0,correctionNet:0,settlementAdjustmentNet:0,platformServiceFeeCost:0,cargoCost:0,stoppageNet:0,sellerRevenue:0,transactions:0,adjustedDays:0,otherFinancialDays:0})
 const adjustedSellerRevenue=acc.sellerRevenue+acc.settlementAdjustmentNet,platformCashBeforeStoppage=adjustedSellerRevenue-acc.platformServiceFeeCost-acc.cargoCost,knownCashAfterFeesAndStoppage=platformCashBeforeStoppage-acc.stoppageNet
 const totals:any={grossSales:money(acc.grossSales),grossReturns:money(acc.grossReturns),commissionCost:money(acc.commissionCost),discountCost:money(acc.discountCost),couponCost:money(acc.couponCost),provisionNet:money(acc.provisionNet),manualRefundNet:money(acc.manualRefundNet),platformPromoNet:money(acc.platformPromoNet),deliveryFeeNet:money(acc.deliveryFeeNet),correctionNet:money(acc.correctionNet),settlementAdjustmentNet:money(acc.settlementAdjustmentNet),platformServiceFeeCost:money(acc.platformServiceFeeCost),cargoCost:money(acc.cargoCost),stoppageNet:money(acc.stoppageNet),sellerRevenue:money(acc.sellerRevenue),adjustedSellerRevenue:money(adjustedSellerRevenue),platformCashBeforeStoppage:money(platformCashBeforeStoppage),knownCashAfterFeesAndStoppage:money(knownCashAfterFeesAndStoppage),knownFeeNet:money(knownCashAfterFeesAndStoppage),transactions:acc.transactions,netSales:money(acc.grossSales-acc.grossReturns),returnRate:acc.grossSales?acc.grossReturns/acc.grossSales*100:0,commissionRate:acc.grossSales?acc.commissionCost/acc.grossSales*100:0}
 const pm=new Map<string,any>();for(const r of products){const id=String(r.external_product_id||r.barcode||'').trim();if(!id)continue;const p=pm.get(id)||{externalProductId:id,sku:r.sku||null,barcode:r.barcode||id,name:r.product_name||null,units:0,salesUnits:0,returnUnits:0,orderLineMatches:0,returnProxyMatches:0,claimItemMatches:0,unitBases:new Set<string>(),salesBases:new Set<string>(),returnBases:new Set<string>(),grossSales:0,grossReturns:0,commissionCost:0,sellerRevenue:0,knownCogs:0,estimatedProfit:0,profitRows:0,rowCount:0,confidence:'platform_only'};p.rowCount++;p.units+=signedInt(r.units);p.salesUnits+=posInt(r.sales_units);p.returnUnits+=posInt(r.return_units);p.orderLineMatches+=posInt(r.order_line_matches);p.returnProxyMatches+=posInt(r.return_proxy_matches);p.claimItemMatches+=posInt(r.claim_item_matches);p.unitBases.add(String(r.unit_basis||'settlement_transaction_proxy'));p.salesBases.add(String(r.sales_unit_basis||'settlement_transaction_proxy'));p.returnBases.add(String(r.return_unit_basis||'settlement_transaction_proxy'));p.grossSales+=cents(r.gross_sales);p.grossReturns+=cents(r.gross_returns);p.commissionCost+=cents(r.commission_cost);p.sellerRevenue+=cents(r.seller_revenue);if(r.known_cogs!==null)p.knownCogs+=cents(r.known_cogs);if(r.estimated_profit!==null){p.estimatedProfit+=cents(r.estimated_profit);p.profitRows++}if(r.profit_confidence==='cost_known')p.confidence='cost_known';if(!p.name&&r.product_name)p.name=r.product_name;if(!p.sku&&r.sku)p.sku=r.sku;pm.set(id,p)}
 const productRows=[...pm.values()].map(p=>{const grossSales=money(p.grossSales),sellerRevenue=money(p.sellerRevenue),profit=p.profitRows?money(p.estimatedProfit):null,cogs=p.profitRows?money(p.knownCogs):null,margin=profit!==null&&sellerRevenue?profit/sellerRevenue*100:null,unitBasis=rankBasis(p.unitBases),salesUnitBasis=rankSales(p.salesBases),returnUnitBasis=rankReturn(p.returnBases);let unitConfidence='proxy';if(salesUnitBasis==='order_v2_quantity'&&returnUnitBasis==='claims_accepted_items')unitConfidence='sales_and_returns_evidence';else if(salesUnitBasis==='order_v2_quantity'&&p.returnUnits===0)unitConfidence='exact_sales';else if(salesUnitBasis==='order_v2_quantity')unitConfidence='exact_sales_return_proxy';else if(salesUnitBasis==='mixed_fallback'||returnUnitBasis==='mixed_fallback')unitConfidence='mixed';return{externalProductId:p.externalProductId,sku:p.sku,barcode:p.barcode,name:p.name,units:p.units,salesUnits:p.salesUnits,returnUnits:p.returnUnits,unitBasis,salesUnitBasis,returnUnitBasis,unitConfidence,orderLineMatches:p.orderLineMatches,returnProxyMatches:p.returnProxyMatches,claimItemMatches:p.claimItemMatches,grossSales,grossReturns:money(p.grossReturns),commissionCost:money(p.commissionCost),sellerRevenue,knownCogs:cogs,estimatedProfit:profit,margin,confidence:p.confidence,costCoverage:p.rowCount?p.profitRows/p.rowCount:0,status:profit===null?'unknown':profit<0?'loss':sellerRevenue&&margin!==null&&margin<10?'risk':'healthy'}})
 const covered=productRows.filter(p=>p.estimatedProfit!==null),missing=productRows.filter(p=>p.estimatedProfit===null),worst=[...covered].sort((a,b)=>(a.estimatedProfit??0)-(b.estimatedProfit??0)).slice(0,10),needsCost=[...missing].sort((a,b)=>b.grossSales-a.grossSales).slice(0,10),productCount=productRows.length,costCovered=covered.length,costCoverage=ratio(costCovered,productCount),totalGross=productRows.reduce((s,p)=>s+Math.max(0,p.grossSales),0),coveredGross=covered.reduce((s,p)=>s+Math.max(0,p.grossSales),0),salesCostCoverage=ratio(coveredGross,totalGross),coveredSellerRevenue=covered.reduce((s,p)=>s+p.sellerRevenue,0),coveredKnownCogs=covered.reduce((s,p)=>s+(p.knownCogs||0),0),coveredProfit=covered.reduce((s,p)=>s+(p.estimatedProfit||0),0),coveredMargin=coveredSellerRevenue?coveredProfit/coveredSellerRevenue*100:null
 const exactSalesGross=products.reduce((s,r)=>s+(r.sales_unit_basis==='order_v2_quantity'?Math.max(0,Number(r.gross_sales)||0):0),0),rawGross=products.reduce((s,r)=>s+Math.max(0,Number(r.gross_sales)||0),0),claimMatchedItems=products.reduce((s,r)=>s+posInt(r.claim_item_matches),0),returnProxyItems=products.reduce((s,r)=>s+posInt(r.return_proxy_matches),0),returnEvidenceApplicable=claimMatchedItems+returnProxyItems>0,salesEvidenceCoverage=ratio(exactSalesGross,rawGross),returnEvidenceCoverage=returnEvidenceApplicable?ratio(claimMatchedItems,claimMatchedItems+returnProxyItems):null,dataConfidence=productCount===0?'no_product_data':salesCostCoverage===0?'platform_only':salesCostCoverage>=.999?'cost_enriched':'partial_cost_coverage'
 const dailyOut=daily.map((r:any)=>{const core=cents(r.seller_revenue),adjust=cents(r.settlement_adjustment_net),platform=cents(r.platform_service_fee_cost),cargo=cents(r.cargo_cost),stoppage=cents(r.stoppage_net),before=core+adjust-platform-cargo,after=before-stoppage;return{day:r.day,currency:r.currency,grossSales:money(cents(r.gross_sales)),grossReturns:money(cents(r.gross_returns)),commissionCost:money(cents(r.commission_cost)),discountCost:money(cents(r.discount_cost)),couponCost:money(cents(r.coupon_cost)),provisionNet:money(cents(r.provision_net)),manualRefundNet:money(cents(r.manual_refund_net)),platformPromoNet:money(cents(r.platform_promo_net)),deliveryFeeNet:money(cents(r.delivery_fee_net)),correctionNet:money(cents(r.correction_net)),settlementAdjustmentNet:money(adjust),platformServiceFeeCost:money(platform),cargoCost:money(cargo),stoppageNet:money(stoppage),sellerRevenue:money(core),adjustedSellerRevenue:money(core+adjust),platformCashBeforeStoppage:money(before),knownCashAfterFeesAndStoppage:money(after),knownFeeNet:money(after),settlementCoverage:r.settlement_coverage||'sale_return_core',otherFinancialCoverage:r.other_financial_coverage||'none',transactions:posInt(r.transaction_count)}})
 return json(200,{connection,rangeDays:days,startDay:start,currency:daily[0]?.currency||'TRY',totals,daily:dailyOut,products:{count:productCount,costCovered,worst,needsCost},profitSnapshot:{coveredProducts:costCovered,totalProducts:productCount,coveredGrossSales:coveredGross,coveredSellerRevenue,coveredKnownCogs,coveredProfit,coveredMargin,scope:'product_contribution_before_unallocated_store_level_costs'},settlementSnapshot:{coverage:acc.adjustedDays===dailyOut.length&&dailyOut.length?'settlement_adjustments_v1':acc.adjustedDays?'partial':'sale_return_core',adjustedDays:acc.adjustedDays,totalDays:dailyOut.length,coreSellerRevenue:money(acc.sellerRevenue),adjustmentNet:money(acc.settlementAdjustmentNet),adjustedSellerRevenue:money(adjustedSellerRevenue)},otherFinancialSnapshot:{coverage:acc.otherFinancialDays===dailyOut.length&&dailyOut.length?'otherfinancials_v1':acc.otherFinancialDays?'partial':'none',coveredDays:acc.otherFinancialDays,totalDays:dailyOut.length,platformServiceFeeCost:money(acc.platformServiceFeeCost),cargoCost:money(acc.cargoCost),stoppageNet:money(acc.stoppageNet),platformCashBeforeStoppage:money(platformCashBeforeStoppage),knownCashAfterFeesAndStoppage:money(knownCashAfterFeesAndStoppage),knownFeeNet:money(knownCashAfterFeesAndStoppage)},unitSnapshot:{totalProducts:productCount,claimMatchedItems,returnProxyItems,salesEvidenceCoverage,returnEvidenceCoverage,returnEvidenceApplicable},dataConfidence,costCoverage,salesCostCoverage,coverage:'settlement_otherfinancials_stoppage_v2',productProfitCoverage:'cost_enriched_product_contribution'},origin)
})
