function rowsToObjects(rows){if(rows.length<2)throw new Error('Dosyada başlık ve en az bir ürün satırı olmalı.');const headers=rows[0].map(canonicalKey);const required=['urun','satis_fiyati','maliyet'];for(const k of required)if(!headers.includes(k))throw new Error(`Zorunlu sütun eksik: ${k}`);return rows.slice(1).filter(r=>r.some(x=>String(x??'').trim()!=='')).map((r,idx)=>{const o={__row:idx+2};headers.forEach((h,i)=>o[h]=r[i]??'');return o})}
function rowNum(row,key,def){const n=parseTRNumber(row[key]);return Number.isFinite(n)?n:def}
function rowToInput(row,defaults){return {salePrice:rowNum(row,'satis_fiyati',NaN),saleVatRate:rowNum(row,'satis_kdv_yuzde',defaults.saleVatRate),productCost:rowNum(row,'maliyet',NaN),purchaseVatRate:rowNum(row,'maliyet_kdv_yuzde',defaults.purchaseVatRate),deductInputVat:boolVal(row.girdi_kdv_indirilebilir,defaults.deductInputVat),commissionRate:rowNum(row,'komisyon_yuzde',defaults.commissionRate),serviceRate:rowNum(row,'hizmet_yuzde',defaults.serviceRate),otherPercentRate:rowNum(row,'diger_kesinti_yuzde',defaults.otherPercentRate),shippingCost:rowNum(row,'kargo',defaults.shippingCost),packagingCost:rowNum(row,'paketleme',defaults.packagingCost),adRate:rowNum(row,'reklam_yuzde',defaults.adRate),otherFixedCost:rowNum(row,'diger_sabit',defaults.otherFixedCost),returnRate:rowNum(row,'iade_yuzde',defaults.returnRate),returnExtraCost:rowNum(row,'iade_ek_maliyet',defaults.returnExtraCost),returnProductLossRate:rowNum(row,'iade_urun_kayip_yuzde',defaults.returnProductLossRate),returnNonRefundedFee:rowNum(row,'iade_geri_alinamayan_gider',defaults.returnNonRefundedFee),minMargin:rowNum(row,'min_marj_yuzde',defaults.minMargin),targetMargin:rowNum(row,'hedef_marj_yuzde',defaults.targetMargin)}}
let bulkResults=[],bulkRawObjects=[];
function rebuildBulkFromRaw(){if(!bulkRawObjects.length)return;const defs=getInputs(),mode=$('analysisMode').value,errors=[];bulkResults=[];for(const row of bulkRawObjects){const v=rowToInput(row,defs),verr=validate(v);if(!Number.isFinite(v.salePrice)||!Number.isFinite(v.productCost)||verr.length){errors.push(`Satır ${row.__row}: ${!Number.isFinite(v.salePrice)?'satış fiyatı okunamadı':!Number.isFinite(v.productCost)?'maliyet okunamadı':verr[0]}`);continue}const e2=engine(v),s2={mode,profit:mode==='vat'?e2.vatProfit:e2.grossProfit,margin:mode==='vat'?e2.vatMargin:e2.grossMargin,revenue:mode==='vat'?e2.netRevenue:e2.grossRevenue,...e2.priceMetrics(mode,v.targetMargin)},c=classify(v,s2),qty=Math.max(0,rowNum(row,'aylik_adet',1));bulkResults.push({name:String(row.urun||'İsimsiz ürün'),qty,v,e:e2,s:s2,c,monthlyImpact:s2.profit*qty})}renderBulk();return errors}
$('bulkFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{$('bulkMessage').textContent='Dosya okunuyor…';let rows;if(file.name.toLowerCase().endsWith('.xlsx'))rows=await parseXLSX(file);else rows=parseCSV(await file.text());bulkRawObjects=rowsToObjects(rows);const errors=rebuildBulkFromRaw()||[];$('exportBtn').disabled=!bulkResults.length;$('bulkMessage').textContent=`${bulkResults.length} ürün analiz edildi.${errors.length?' '+errors.length+' satır atlandı: '+errors.slice(0,3).join(' | ')+(errors.length>3?' …':''):''}`}catch(err){bulkResults=[];bulkRawObjects=[];renderBulk();$('bulkMessage').textContent='Hata: '+err.message}}
function renderBulk(){updateBulkKPIs();const body=$('bulkBody');if(!bulkResults.length){body.innerHTML='<tr><td colspan="8" class="empty">Henüz geçerli ürün analizi yok.</td></tr>';renderDiagnostics();return}const q=$('bulkSearch').value.trim().toLocaleLowerCase('tr-TR'),f=$('bulkFilter').value,sort=$('bulkSort').value;let rows=bulkResults.filter(r=>(!q||r.name.toLocaleLowerCase('tr-TR').includes(q))&&(f==='all'||r.c.key===f));rows=[...rows];if(sort==='impactAsc')rows.sort((a,b)=>a.monthlyImpact-b.monthlyImpact);if(sort==='profitAsc')rows.sort((a,b)=>a.s.profit-b.s.profit);if(sort==='profitDesc')rows.sort((a,b)=>b.s.profit-a.s.profit);if(sort==='marginAsc')rows.sort((a,b)=>a.s.margin-b.s.margin);if(sort==='marginDesc')rows.sort((a,b)=>b.s.margin-a.s.margin);body.innerHTML=rows.map(r=>`<tr><td>${escapeHtml(r.name)}</td><td>${r.qty.toLocaleString('tr-TR')}</td><td>${fmtMoney(r.v.salePrice)}</td><td>${fmtMoney(r.s.profit)}</td><td>${fmtPct(r.s.margin)}</td><td class="${r.monthlyImpact<0?'bad':'good'}">${fmtMoney(r.monthlyImpact)}</td><td>${fmtMoney(r.s.targetPrice)}</td><td class="${r.c.cls}">${r.c.label}</td></tr>`).join('');renderDiagnostics()}
function updateBulkKPIs(){const totalQty=bulkResults.reduce((a,r)=>a+r.qty,0),profit=bulkResults.reduce((a,r)=>a+r.monthlyImpact,0),revenue=bulkResults.reduce((a,r)=>a+r.s.revenue*r.qty,0),margin=revenue>0?profit/revenue*100:NaN;$('kpiProducts').textContent=bulkResults.length;$('kpiLoss').textContent=bulkResults.filter(r=>r.c.key==='loss').length;$('kpiRisk').textContent=bulkResults.filter(r=>r.c.key==='risk').length;$('kpiMargin').textContent=fmtPct(margin);$('kpiProfit').textContent=bulkResults.length?fmtMoney(profit):'—'}
function renderDiagnostics(){const p=$('problemList'),d=$('diagnostics');if(!bulkResults.length){p.innerHTML=d.innerHTML='<div class="empty">Analiz bekleniyor.</div>';return}const worst=[...bulkResults].sort((a,b)=>a.monthlyImpact-b.monthlyImpact).slice(0,5);p.innerHTML=worst.map(r=>`<div class="recommendation"><strong>${escapeHtml(r.name)} <span class="pill">${fmtMoney(r.monthlyImpact)}/ay</span></strong><p>${r.s.profit<0?`Sipariş başına ${fmtMoney(Math.abs(r.s.profit))} zarar. Başa baş için yaklaşık ${fmtMoney(r.s.breakEven)}.`:`Marj ${fmtPct(r.s.margin)}. Hedef ${fmtPct(r.v.targetMargin)} için yaklaşık ${fmtMoney(r.s.targetPrice)}.`}</p></div>`).join('');const loss=bulkResults.filter(r=>r.c.key==='loss').length,risk=bulkResults.filter(r=>r.c.key==='risk').length;const feeHeavy=bulkResults.filter(r=>(r.e.platformFees+r.e.adCost)>Math.max(0,r.s.revenue)*.25).length;const returnHeavy=bulkResults.filter(r=>r.v.returnRate>=10).length;d.innerHTML=[loss?`${loss} ürün doğrudan zarar ediyor.`:'Doğrudan zarar eden ürün görünmüyor.',risk?`${risk} ürün minimum marj hedefinin altında.`:'Riskli marj sınıfında ürün görünmüyor.',feeHeavy?`${feeHeavy} üründe platform + reklam yükü gerçekleşen gelirin %25’inden yüksek.`:'Kesinti yükü genel olarak kontrol altında.',returnHeavy?`${returnHeavy} üründe iade varsayımı %10 veya üzeri; sonuçlar iade maliyetine hassas.`:'Yüksek iade varsayımı olan ürün az.'].map((x,i)=>`<div class="recommendation"><strong>${['Portföy riski','Marj disiplini','Kesinti yükü','İade hassasiyeti'][i]}</strong><p>${x}</p></div>`).join('')}
['bulkSearch','bulkFilter','bulkSort'].forEach(id=>$(id).addEventListener('input',renderBulk));
function csvSafe(v,untrusted=false){if(typeof v==='number'&&Number.isFinite(v))return String(v);let s=String(v??'').replace(/"/g,'""');if(untrusted&&/^[=+\-@]/.test(s))s="'"+s;return '"'+s+'"'}function downloadText(name,text){const blob=new Blob([text],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
$('downloadSampleBtn').onclick=()=>downloadText('karkalkan-v3-ornek.csv','\uFEFF'+['urun;aylik_adet;satis_fiyati;maliyet;komisyon_yuzde;hizmet_yuzde;kargo;paketleme;reklam_yuzde;iade_yuzde','Telefon Kılıfı;120;249;90;20;1;42;5;6;5','Bluetooth Kulaklık;45;699;390;17;1;55;7;8;4','Masa Lambası;70;499;230;18;1;48;6;5;2'].join('\n'));
$('exportBtn').onclick=()=>{if(!bulkResults.length)return;const h=['urun','aylik_adet','satis_fiyati','kar_siparis','marj_yuzde','aylik_etki','basa_bas_fiyat','hedef_fiyat','durum'];const lines=[h.map(x=>csvSafe(x)).join(';'),...bulkResults.map(r=>[csvSafe(r.name,true),csvSafe(r.qty),csvSafe(r.v.salePrice),csvSafe(r.s.profit),csvSafe(r.s.margin),csvSafe(r.monthlyImpact),csvSafe(r.s.breakEven),csvSafe(r.s.targetPrice),csvSafe(r.c.label)].join(';'))];downloadText('karkalkan-v3-sonuclar.csv','\uFEFF'+lines.join('\n'))};

function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#096;')}
$('demoBtn').onclick=()=>{applyValues({salePrice:899,saleVatRate:20,productCost:470,purchaseVatRate:20,deductInputVat:true,commissionRate:18,serviceRate:1,otherPercentRate:0,shippingCost:58,packagingCost:8,adRate:7,otherFixedCost:12,minMargin:12,targetMargin:20,returnRate:6,returnExtraCost:48,returnProductLossRate:8,returnNonRefundedFee:5,discountRate:15,campaignExtraAd:3,campaignPerOrderCost:4,campaignTotalBudget:1800,baseUnits:120,salesLift:55});location.hash='#motor'};

for(const el of document.querySelectorAll('input,select')){if(['bulkFile','bulkSearch','bulkFilter','bulkSort','scenarioSelect','profileName','scenarioName'].includes(el.id))continue;el.addEventListener('input',()=>{render();if(bulkRawObjects.length)rebuildBulkFromRaw()});el.addEventListener('change',()=>{render();if(bulkRawObjects.length)rebuildBulkFromRaw()})}
renderScenarioSelect();renderProfiles();render();
