function loadJSON(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}function saveJSON(key,obj){localStorage.setItem(key,JSON.stringify(obj))}
function feeSnapshot(){const v=getInputs();return {commissionRate:v.commissionRate,serviceRate:v.serviceRate,otherPercentRate:v.otherPercentRate,shippingCost:v.shippingCost,packagingCost:v.packagingCost,adRate:v.adRate,otherFixedCost:v.otherFixedCost,returnRate:v.returnRate,returnExtraCost:v.returnExtraCost,returnProductLossRate:v.returnProductLossRate,returnNonRefundedFee:v.returnNonRefundedFee}}
function applyValues(obj){for(const [k,v] of Object.entries(obj)){const el=$(k);if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v}render()}
function renderProfiles(){const profiles=loadJSON(PROFILE_KEY),list=$('profileList'),body=$('profileCompareBody');const names=Object.keys(profiles);if(!names.length){list.innerHTML='<div class="empty">Henüz profil yok.</div>';body.innerHTML='<tr><td colspan="5" class="empty">Profil kaydettiğinde karşılaştırma burada görünür.</td></tr>';return}
 list.innerHTML=names.map(n=>`<div class="profile-chip"><span>${escapeHtml(n)}</span><div><button class="btn ghost" data-apply-profile="${encodeURIComponent(n)}">Uygula</button> <button class="btn ghost" data-delete-profile="${encodeURIComponent(n)}">Sil</button></div></div>`).join('');
 const base=getInputs();body.innerHTML=names.map(n=>{const vv={...base,...profiles[n]},e=engine(vv),s=selectedResult(vv,e),c=classify(vv,s);return `<tr><td>${escapeHtml(n)}</td><td>${fmtMoney(s.profit)}</td><td>${fmtPct(s.margin)}</td><td>${fmtMoney(s.breakEven)}</td><td class="${c.cls}">${c.label}</td></tr>`}).join('');
 list.querySelectorAll('[data-apply-profile]').forEach(b=>b.onclick=()=>applyValues(profiles[decodeURIComponent(b.dataset.applyProfile)]));list.querySelectorAll('[data-delete-profile]').forEach(b=>b.onclick=()=>{const p=loadJSON(PROFILE_KEY);delete p[decodeURIComponent(b.dataset.deleteProfile)];saveJSON(PROFILE_KEY,p);renderProfiles()})}
$('saveProfileBtn').onclick=()=>{const n=$('profileName').value.trim();if(!n){$('profileName').focus();return}const p=loadJSON(PROFILE_KEY);p[n]=feeSnapshot();saveJSON(PROFILE_KEY,p);$('profileName').value='';renderProfiles()};

function scenarioSnapshot(){return {...getInputs(),analysisMode:$('analysisMode').value,...campaignInputs()}}
function renderScenarioSelect(){const s=loadJSON(SCENARIO_KEY),sel=$('scenarioSelect'),cur=sel.value;sel.innerHTML='<option value="">Kayıtlı senaryolar</option>'+Object.keys(s).map(n=>`<option value="${escapeAttr(n)}">${escapeHtml(n)}</option>`).join('');if(s[cur])sel.value=cur}
$('saveScenarioBtn').onclick=()=>{const n=$('scenarioName').value.trim();if(!n){$('scenarioName').focus();return}const s=loadJSON(SCENARIO_KEY);s[n]=scenarioSnapshot();saveJSON(SCENARIO_KEY,s);renderScenarioSelect();$('scenarioSelect').value=n};
$('scenarioSelect').onchange=()=>{const s=loadJSON(SCENARIO_KEY),x=s[$('scenarioSelect').value];if(x){if(x.analysisMode)$('analysisMode').value=x.analysisMode;applyValues(x)}};
$('deleteScenarioBtn').onclick=()=>{const n=$('scenarioSelect').value;if(!n)return;const s=loadJSON(SCENARIO_KEY);delete s[n];saveJSON(SCENARIO_KEY,s);renderScenarioSelect()};

function normalizeHeader(h){return String(h??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
const aliases={urun:['urun','urun_adi','product','product_name'],satis_fiyati:['satis_fiyati','fiyat','sale_price'],maliyet:['maliyet','urun_maliyeti','cost','product_cost'],aylik_adet:['aylik_adet','adet','monthly_units','quantity'],satis_kdv_yuzde:['satis_kdv_yuzde','kdv','satis_kdv'],maliyet_kdv_yuzde:['maliyet_kdv_yuzde','alis_kdv','maliyet_kdv'],girdi_kdv_indirilebilir:['girdi_kdv_indirilebilir','kdv_indirilebilir'],komisyon_yuzde:['komisyon_yuzde','komisyon'],hizmet_yuzde:['hizmet_yuzde','hizmet_bedeli_yuzde'],diger_kesinti_yuzde:['diger_kesinti_yuzde','diger_kesinti'],kargo:['kargo','kargo_maliyeti'],paketleme:['paketleme','paketleme_maliyeti'],reklam_yuzde:['reklam_yuzde','reklam'],diger_sabit:['diger_sabit','diger_gider'],iade_yuzde:['iade_yuzde','iade_orani'],iade_ek_maliyet:['iade_ek_maliyet','iade_maliyeti'],iade_urun_kayip_yuzde:['iade_urun_kayip_yuzde','iade_urun_kayip'],iade_geri_alinamayan_gider:['iade_geri_alinamayan_gider','iade_geri_alinmayan'],min_marj_yuzde:['min_marj_yuzde','minimum_marj'],hedef_marj_yuzde:['hedef_marj_yuzde','hedef_marj']};
function canonicalKey(h){const n=normalizeHeader(h);for(const [k,arr] of Object.entries(aliases))if(arr.includes(n))return k;return n}
function detectDelimiter(line){let comma=0,semi=0,quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){i++;continue}quoted=!quoted}else if(!quoted){if(c===',')comma++;if(c===';')semi++}}return semi>=comma?';':','}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const delim=detectDelimiter(text.split(/\r?\n/,1)[0]);const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else{if(c==='"')quoted=true;else if(c===delim){row.push(field);field=''}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=c}}if(field.length||row.length){row.push(field);rows.push(row)}return rows.filter(r=>r.some(x=>String(x).trim()!==''))}

async function unzipEntry(buf,entry){
 const limit=typeof KK_SECURITY_LIMITS!=='undefined'?KK_SECURITY_LIMITS.maxZipEntryUncompressed:16*1024*1024;
 if(!(buf instanceof ArrayBuffer)||!entry||!Number.isFinite(entry.dataStart)||!Number.isFinite(entry.compressedSize))throw new Error('XLSX ZIP girdisi geçersiz.');
 if(entry.dataStart<0||entry.compressedSize<0||entry.dataStart+entry.compressedSize>buf.byteLength)throw new Error('XLSX ZIP veri aralığı geçersiz.');
 const data=new Uint8Array(buf,entry.dataStart,entry.compressedSize);
 if(entry.method===0){if(data.byteLength>limit)throw new Error('XLSX girdisi güvenli açma sınırını aşıyor.');return data}
 if(entry.method!==8)throw new Error('XLSX içinde desteklenmeyen sıkıştırma yöntemi.');
 if(typeof DecompressionStream==='undefined')throw new Error('Bu tarayıcı XLSX açmak için gerekli yerel sıkıştırma API’sini desteklemiyor. CSV kullanabilirsin.');
 const ds=new DecompressionStream('deflate-raw'),reader=new Blob([data]).stream().pipeThrough(ds).getReader(),chunks=[];let total=0;
 try{for(;;){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>limit){await reader.cancel();throw new Error('XLSX açılırken güvenli veri sınırı aşıldı.')}chunks.push(value)}}finally{reader.releaseLock()}
 const out=new Uint8Array(total);let pos=0;for(const chunk of chunks){out.set(chunk,pos);pos+=chunk.byteLength}return out
}
function zipEntries(buf){
 if(!(buf instanceof ArrayBuffer)||buf.byteLength<22)throw new Error('Geçerli XLSX/ZIP yapısı bulunamadı.');
 const dv=new DataView(buf);let eocd=-1;for(let i=buf.byteLength-22;i>=Math.max(0,buf.byteLength-65557);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}}
 if(eocd<0||eocd+22>buf.byteLength)throw new Error('Geçerli XLSX/ZIP yapısı bulunamadı.');
 const count=dv.getUint16(eocd+10,true),offset=dv.getUint32(eocd+16,true),maxEntries=typeof KK_SECURITY_LIMITS!=='undefined'?KK_SECURITY_LIMITS.maxZipEntries:500,dec=new TextDecoder();
 if(count>maxEntries)throw new Error('XLSX içinde olağandışı sayıda ZIP girdisi var.');
 if(count&&offset>buf.byteLength-46)throw new Error('XLSX merkezi dizin konumu geçersiz.');
 let p=offset;const out={};for(let n=0;n<count;n++){
  if(p<0||p+46>buf.byteLength||dv.getUint32(p,true)!==0x02014b50)throw new Error('XLSX merkezi dizini bozuk.');
  const method=dv.getUint16(p+10,true),comp=dv.getUint32(p+20,true),uncomp=dv.getUint32(p+24,true),fn=dv.getUint16(p+28,true),ex=dv.getUint16(p+30,true),co=dv.getUint16(p+32,true),local=dv.getUint32(p+42,true),next=p+46+fn+ex+co;
  if(next>buf.byteLength||local+30>buf.byteLength||dv.getUint32(local,true)!==0x04034b50)throw new Error('XLSX ZIP başlığı geçersiz.');
  const name=dec.decode(new Uint8Array(buf,p+46,fn));if(!name||Object.prototype.hasOwnProperty.call(out,name))throw new Error('XLSX içinde geçersiz veya yinelenen ZIP girdisi var.');
  const lfn=dv.getUint16(local+26,true),lex=dv.getUint16(local+28,true),dataStart=local+30+lfn+lex;if(dataStart>buf.byteLength||dataStart+comp>buf.byteLength)throw new Error('XLSX ZIP veri aralığı geçersiz.');
  out[name]={method,compressedSize:comp,uncompressedSize:uncomp,dataStart};p=next
 }
 return out
}
function colIndex(ref){const m=String(ref).match(/^([A-Z]+)/i);if(!m)return 0;let n=0;for(const ch of m[1].toUpperCase())n=n*26+ch.charCodeAt(0)-64;return n-1}
function xmlEls(node,name){return [...node.getElementsByTagNameNS('*',name)]}
async function parseXLSX(file){const buf=await file.arrayBuffer(),entries=zipEntries(buf),dec=new TextDecoder('utf-8');let shared=[];if(entries['xl/sharedStrings.xml']){const xml=dec.decode(await unzipEntry(buf,entries['xl/sharedStrings.xml'])),doc=new DOMParser().parseFromString(xml,'application/xml');if(xmlEls(doc,'parsererror').length)throw new Error('XLSX sharedStrings XML okunamadı.');shared=xmlEls(doc,'si').map(si=>xmlEls(si,'t').map(t=>t.textContent||'').join(''))}
 const sheetName=Object.keys(entries).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort()[0];if(!sheetName)throw new Error('XLSX içinde çalışma sayfası bulunamadı.');const xml=dec.decode(await unzipEntry(buf,entries[sheetName])),doc=new DOMParser().parseFromString(xml,'application/xml');if(xmlEls(doc,'parsererror').length)throw new Error('XLSX çalışma sayfası XML’i okunamadı.');const rows=[];for(const rowEl of xmlEls(doc,'row')){const arr=[];for(const c of xmlEls(rowEl,'c')){const idx=colIndex(c.getAttribute('r')),t=c.getAttribute('t');let value='';if(t==='inlineStr'){value=xmlEls(c,'t').map(x=>x.textContent||'').join('')}else{const ve=xmlEls(c,'v')[0];const raw=ve?ve.textContent:'';value=t==='s'?shared[Number(raw)]??raw:raw}arr[idx]=value}rows.push(arr)}return rows}

// Defensive localStorage handling: schema validation, safe keys and bounded record count.
const KK_MAX_SAVED_RECORDS=50,KK_MAX_STORAGE_BYTES=256*1024;
const KK_PROFILE_FIELDS=new Set(['commissionRate','serviceRate','otherPercentRate','shippingCost','packagingCost','adRate','otherFixedCost','returnRate','returnExtraCost','returnProductLossRate','returnNonRefundedFee']);
const KK_SCENARIO_FIELDS=new Set(['salePrice','saleVatRate','productCost','purchaseVatRate','deductInputVat','commissionRate','serviceRate','otherPercentRate','shippingCost','packagingCost','adRate','otherFixedCost','minMargin','targetMargin','returnRate','returnExtraCost','returnProductLossRate','returnNonRefundedFee','analysisMode','discountRate','campaignExtraAd','campaignPerOrderCost','campaignTotalBudget','baseUnits','salesLift']);
function kkSafeRecordName(name){const s=String(name??'').trim();return s&&s.length<=80&&!['__proto__','prototype','constructor'].includes(s.toLowerCase())?s:null}
function kkIsPlainObject(v){if(!v||typeof v!=='object'||Array.isArray(v))return false;const p=Object.getPrototypeOf(v);return p===Object.prototype||p===null}
function kkCleanSavedValue(v,allowed){if(!kkIsPlainObject(v))return null;const out=Object.create(null);for(const [k,x] of Object.entries(v)){if(!allowed.has(k))continue;if(k==='analysisMode'){if(x==='gross'||x==='vat')out[k]=x;continue}if(k==='deductInputVat'){out[k]=!!x;continue}const n=typeof x==='number'?x:parseTRNumber(x);if(Number.isFinite(n)&&Math.abs(n)<=1e12)out[k]=n}return out}
const kkLegacyLoadJSON=loadJSON;loadJSON=function(key){try{const raw=localStorage.getItem(key)||'{}';if(raw.length>KK_MAX_STORAGE_BYTES){localStorage.removeItem(key);return Object.create(null)}const parsed=JSON.parse(raw);if(!kkIsPlainObject(parsed))return Object.create(null);const allowed=key===PROFILE_KEY?KK_PROFILE_FIELDS:key===SCENARIO_KEY?KK_SCENARIO_FIELDS:null;if(!allowed)return Object.create(null);const out=Object.create(null);let count=0;for(const [name,val] of Object.entries(parsed)){if(count>=KK_MAX_SAVED_RECORDS)break;const safe=kkSafeRecordName(name),clean=safe&&kkCleanSavedValue(val,allowed);if(safe&&clean){out[safe]=clean;count++}}return out}catch{return Object.create(null)}};
const kkLegacySaveJSON=saveJSON;saveJSON=function(key,obj){if(!kkIsPlainObject(obj))return;const allowed=key===PROFILE_KEY?KK_PROFILE_FIELDS:key===SCENARIO_KEY?KK_SCENARIO_FIELDS:null;if(!allowed)return;const clean=Object.create(null);let count=0;for(const [name,val] of Object.entries(obj)){if(count>=KK_MAX_SAVED_RECORDS)break;const safe=kkSafeRecordName(name),v=safe&&kkCleanSavedValue(val,allowed);if(safe&&v){clean[safe]=v;count++}}const text=JSON.stringify(clean);if(text.length<=KK_MAX_STORAGE_BYTES)localStorage.setItem(key,text)};
const kkLegacyApplyValues=applyValues;applyValues=function(obj){if(!kkIsPlainObject(obj))return;return kkLegacyApplyValues(obj)};
