function loadJSON(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}function saveJSON(key,obj){localStorage.setItem(key,JSON.stringify(obj))}
function feeSnapshot(){const v=getInputs();return {commissionRate:v.commissionRate,serviceRate:v.serviceRate,otherPercentRate:v.otherPercentRate,shippingCost:v.shippingCost,packagingCost:v.packagingCost,adRate:v.adRate,otherFixedCost:v.otherFixedCost,returnRate:v.returnRate,returnExtraCost:v.returnExtraCost,returnProductLossRate:v.returnProductLossRate,returnNonRefundedFee:v.returnNonRefundedFee}}
function applyValues(obj){for(const [k,v] of Object.entries(obj)){const el=$(k);if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v}render()}
function renderProfiles(){const profiles=loadJSON(PROFILE_KEY),list=$('profileList'),body=$('profileCompareBody');const names=Object.keys(profiles);if(!names.length){list.innerHTML='<div class="empty">Henüz profil yok.</div>';body.innerHTML='<tr><td colspan="5" class="empty">Profil kaydettiğinde karşılaştırma burada görünür.</td></tr>';return}
 list.innerHTML=names.map(n=>`<div class="profile-chip"><span>${escapeHtml(n)}</span><div><button class="btn ghost" data-apply-profile="${encodeURIComponent(n)}">Uygula</button> <button class="btn ghost" data-delete-profile="${encodeURIComponent(n)}">Sil</button></div></div>`).join('');
 const base=getInputs();body.innerHTML=names.map(n=>{const vv={...base,...profiles[n]},e=engine(vv),s=selectedResult(vv,e),c=classify(vv,s);return `<tr><td>${escapeHtml(n)}</td><td>${fmtMoney(s.profit)}</td><td>${fmtPct(s.margin)}</td><td>${fmtMoney(s.breakEven)}</td><td class="${c.cls}">${c.label}</td></tr>`}).join('');
 list.querySelectorAll('[data-apply-profile]').forEach(b=>b.onclick=()=>applyValues(profiles[decodeURIComponent(b.dataset.applyProfile)]));list.querySelectorAll('[data-delete-profile]').forEach(b=>b.onclick=()=>{const p=loadJSON(PROFILE_KEY);delete p[decodeURIComponent(b.dataset.deleteProfile)];saveJSON(PROFILE_KEY,p);renderProfiles()})}
$('saveProfileBtn').onclick=()=>{const n=$('profileName').value.trim();if(!n){$('profileName').focus();return}const p=loadJSON(PROFILE_KEY);p[n]=feeSnapshot();saveJSON(PROFILE_KEY,p);$('profileName').value='';renderProfiles()};

function scenarioSnapshot(){return {...getInputs(),analysisMode:$('analysisMode').value,...campaignInputs()}}
function renderScenarioSelect(){const s=loadJSON(SCENARIO_KEY),sel=$('scenarioSelect'),cur=sel.value;sel.innerHTML='<option value="">Kayıtlı senaryolar</option>'+Object.keys(s).map(n=>`<option value="${escapeAttr(n)}">${escapeHtml(n)}</option>`).join('');if(s[cur])sel.value=cur}
$('saveScenarioBtn').onclick=()=>{const n=$('scenarioName').value.trim();if(!n){$('scenarioName').focus();return}const s=loadJSON(SCENARIO_KEY);s[n]=scenarioSnapshot();saveJSON(SCENARIO_KEY,s);renderScenarioSelect();$('scenarioSelect').value=n};
$('scenarioSelect').onchange=()=>{const s=loadJSON(SCENARIO_KEY),x=s[$('scenarioSelect').value];if(x){if(x.analysisMode)$('analysisMode').value=x.analysisMode;applyValues(x)}};
$('deleteScenarioBtn').onclick=()=>{const n=$('scenarioSelect').value;if(!n)return;const s=loadJSON(SCENARIO_KEY);delete s[n];saveJSON(SCENARIO_KEY,s);renderScenarioSelect()};

function normalizeHeader(h){return String(h??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
const aliases={urun:['urun','urun_adi','product','product_name'],satis_fiyati:['satis_fiyati','fiyat','sale_price'],maliyet:['maliyet','urun_maliyeti','cost','product_cost'],aylik_adet:['aylik_adet','adet','monthly_units','quantity'],satis_kdv_yuzde:['satis_kdv_yuzde','kdv','satis_kdv'],maliyet_kdv_yuzde:['maliyet_kdv_yuzde','alis_kdv','maliyet_kdv'],girdi_kdv_indirilebilir:['girdi_kdv_indirilebilir','kdv_indirilebilir'],komisyon_yuzde:['komisyon_yuzde','komisyon'],hizmet_yuzde:['hizmet_yuzde','hizmet_bedeli_yuzde'],diger_kesinti_yuzde:['diger_kesinti_yuzde','diger_kesinti'],kargo:['kargo','kargo_maliyeti'],paketleme:['paketleme','paketleme_maliyeti'],reklam_yuzde:['reklam_yuzde','reklam'],diger_sabit:['diger_sabit','diger_gider'],iade_yuzde:['iade_yuzde','iade_orani'],iade_ek_maliyet:['iade_ek_maliyet','iade_maliyeti'],iade_urun_kayip_yuzde:['iade_urun_kayip_yuzde','iade_urun_kayip'],iade_geri_alinamayan_gider:['iade_geri_alinamayan_gider','iade_geri_alinmayan'],min_marj_yuzde:['min_marj_yuzde','minimum_marj'],hedef_marj_yuzde:['hedef_marj_yuzde','hedef_marj']};
function canonicalKey(h){const n=normalizeHeader(h);for(const [k,arr] of Object.entries(aliases))if(arr.includes(n))return k;return n}
function detectDelimiter(line){let comma=0,semi=0,quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){i++;continue}quoted=!quoted}else if(!quoted){if(c===',')comma++;if(c===';')semi++}}return semi>=comma?';':','}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const delim=detectDelimiter(text.split(/\r?\n/,1)[0]);const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else{if(c==='"')quoted=true;else if(c===delim){row.push(field);field=''}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=c}}if(field.length||row.length){row.push(field);rows.push(row)}return rows.filter(r=>r.some(x=>String(x).trim()!==''))}

async function unzipEntry(buf,entry){const data=new Uint8Array(buf,entry.dataStart,entry.compressedSize);if(entry.method===0)return data;if(entry.method!==8)throw new Error('XLSX içinde desteklenmeyen sıkıştırma yöntemi.');if(typeof DecompressionStream==='undefined')throw new Error('Bu tarayıcı XLSX açmak için gerekli yerel sıkıştırma API’sini desteklemiyor. CSV kullanabilirsin.');const ds=new DecompressionStream('deflate-raw');const stream=new Blob([data]).stream().pipeThrough(ds);return new Uint8Array(await new Response(stream).arrayBuffer())}
function zipEntries(buf){const dv=new DataView(buf);let eocd=-1;for(let i=buf.byteLength-22;i>=Math.max(0,buf.byteLength-65557);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error('Geçerli XLSX/ZIP yapısı bulunamadı.');const count=dv.getUint16(eocd+10,true),offset=dv.getUint32(eocd+16,true),dec=new TextDecoder();let p=offset;const out={};for(let n=0;n<count;n++){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),comp=dv.getUint32(p+20,true),uncomp=dv.getUint32(p+24,true),fn=dv.getUint16(p+28,true),ex=dv.getUint16(p+30,true),co=dv.getUint16(p+32,true),local=dv.getUint32(p+42,true);const name=dec.decode(new Uint8Array(buf,p+46,fn));const lfn=dv.getUint16(local+26,true),lex=dv.getUint16(local+28,true);out[name]={method,compressedSize:comp,uncompressedSize:uncomp,dataStart:local+30+lfn+lex};p+=46+fn+ex+co}return out}
function colIndex(ref){const m=String(ref).match(/^([A-Z]+)/i);if(!m)return 0;let n=0;for(const ch of m[1].toUpperCase())n=n*26+ch.charCodeAt(0)-64;return n-1}
function xmlEls(node,name){return [...node.getElementsByTagNameNS('*',name)]}
async function parseXLSX(file){const buf=await file.arrayBuffer(),entries=zipEntries(buf),dec=new TextDecoder('utf-8');let shared=[];if(entries['xl/sharedStrings.xml']){const xml=dec.decode(await unzipEntry(buf,entries['xl/sharedStrings.xml'])),doc=new DOMParser().parseFromString(xml,'application/xml');if(xmlEls(doc,'parsererror').length)throw new Error('XLSX sharedStrings XML okunamadı.');shared=xmlEls(doc,'si').map(si=>xmlEls(si,'t').map(t=>t.textContent||'').join(''))}
 const sheetName=Object.keys(entries).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort()[0];if(!sheetName)throw new Error('XLSX içinde çalışma sayfası bulunamadı.');const xml=dec.decode(await unzipEntry(buf,entries[sheetName])),doc=new DOMParser().parseFromString(xml,'application/xml');if(xmlEls(doc,'parsererror').length)throw new Error('XLSX çalışma sayfası XML’i okunamadı.');const rows=[];for(const rowEl of xmlEls(doc,'row')){const arr=[];for(const c of xmlEls(rowEl,'c')){const idx=colIndex(c.getAttribute('r')),t=c.getAttribute('t');let value='';if(t==='inlineStr'){value=xmlEls(c,'t').map(x=>x.textContent||'').join('')}else{const ve=xmlEls(c,'v')[0];const raw=ve?ve.textContent:'';value=t==='s'?shared[Number(raw)]??raw:raw}arr[idx]=value}rows.push(arr)}return rows}
