'use strict';

(() => {
  const SECTION_ID='fxImport';
  const STYLE_ID='karkalkan-fx-import-style';
  const REQUIRED=['day','currency','external_product_id','sales_units','gross_sales'];
  const ALLOWED=new Set(['day','settlement_day','currency','external_product_id','sku','product_name','sales_units','return_units','gross_sales','gross_returns','commission_cost','discount_cost','coupon_cost','seller_revenue']);
  const MAX_FILE_BYTES=2_500_000,MAX_ROWS=5000;
  let rows=[];

  function style(){if(document.getElementById(STYLE_ID))return;const link=document.createElement('link');link.id=STYLE_ID;link.rel='stylesheet';link.href='/fx-import.css?v=20260821';document.head.appendChild(link)}
  function requestFn(){if(typeof globalThis.functionRequest==='function')return globalThis.functionRequest;try{if(typeof functionRequest==='function')return functionRequest}catch{}return null}
  function connectionId(){return String(document.getElementById('connectionSelect')?.value||'').trim()}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function status(message,kind=''){const el=document.getElementById('fxImportStatus');if(!el)return;el.textContent=message;el.className=`fx-import-status${kind?` ${kind}`:''}`}
  function nav(){const side=document.querySelector('.side-nav');if(!side||side.querySelector('a[href="#fxImport"]'))return;const anchor=side.querySelector('a[href="#smartCsv"]')||side.querySelector('a[href="#financeAi"]');const link=document.createElement('a');link.href='#fxImport';link.innerHTML='<span>FX</span> Çoklu para';anchor?.insertAdjacentElement('afterend',link)}
  function shell(){if(document.getElementById(SECTION_ID))return;const anchor=document.getElementById('smartCsv')||document.getElementById('financeAi')||document.getElementById('dashboard');if(!anchor)return;const section=document.createElement('section');section.id=SECTION_ID;section.className='section fx-import-section';section.innerHTML=`<div class="fx-import-shell"><div class="fx-import-head"><div><p class="eyebrow">ÇOKLU PARA · FX KANITI</p><h2>Orijinal para birimini koruyarak TRY’ye normalize et</h2><p>USD, EUR, GBP ve desteklenen diğer ECB para birimlerini işlem gününün resmi ECB referans oranıyla TRY’ye çevirir. Orijinal tutarlar ayrı audit kanıtında korunur.</p></div><span class="fx-import-chip">ECB · referans oran</span></div><div class="fx-import-disclaimer"><strong>Kur gerçeği:</strong> ECB referans oranları bilgi amaçlıdır; banka/ödeme sağlayıcısının gerçekleşmiş kuru değildir. Settlement tarihi verilirse gösterilen FX farkı yalnız referans kur farkıdır.</div><div class="fx-import-grid"><label><strong>Normalize çoklu-para CSV</strong><span>Zorunlu: day, currency, external_product_id, sales_units, gross_sales. Opsiyonel settlement_day ile referans FX farkı hesaplanır.</span><input id="fxImportFile" type="file" accept=".csv,text/csv,text/plain"></label><div class="fx-import-template"><strong>Desteklenen kolonlar</strong><code>day,settlement_day,currency,external_product_id,sku,product_name,sales_units,return_units,gross_sales,gross_returns,commission_cost,discount_cost,coupon_cost,seller_revenue</code><button id="fxTemplateBtn" type="button">Örnek şablon indir</button></div></div><div id="fxImportStatus" class="fx-import-status">Dosya bekleniyor.</div><div id="fxImportPreview" class="fx-import-preview fx-import-hidden"></div><div class="fx-import-actions"><span id="fxImportMeta"></span><button id="fxImportBtn" type="button" disabled>ECB kuru ile içe aktar</button></div></div>`;anchor.insertAdjacentElement('afterend',section)}
  function firstRecord(text){let quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){i++;continue}quoted=!quoted}else if((c==='\n'||c==='\r')&&!quoted)return text.slice(0,i)}return text}
  function delimiter(text){return [',',';','\t'].map(char=>[char,(firstRecord(text).split(char).length-1)]).sort((a,b)=>b[1]-a[1])[0][0]}
  function parse(text){const source=String(text||'').replace(/^\uFEFF/,'');if(!source.trim())throw new Error('EMPTY');const sep=delimiter(source),records=[];let row=[],field='',quoted=false;for(let i=0;i<=source.length;i++){const c=i===source.length?'\n':source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){field+='"';i++}else quoted=!quoted;continue}if(c===sep&&!quoted){row.push(field);field='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(field);field='';if(row.some(value=>String(value).trim()!==''))records.push(row);row=[];continue}field+=c}if(quoted||records.length<2)throw new Error('CSV_INVALID');const headers=records[0].map(value=>String(value).trim().toLowerCase());if(headers.some((header,index)=>!header||!ALLOWED.has(header)||headers.indexOf(header)!==index))throw new Error('HEADERS_INVALID');for(const required of REQUIRED)if(!headers.includes(required))throw new Error(`MISSING_${required}`);const output=[];for(let i=1;i<records.length;i++){if(records[i].length!==headers.length)throw new Error(`ROW_${i+1}`);const item={};headers.forEach((header,index)=>item[header]=String(records[i][index]??'').trim());output.push(item);if(output.length>MAX_ROWS)throw new Error('TOO_MANY')}return {headers,rows:output}}
  function human(error){const code=String(error?.message||error||'');if(code.startsWith('MISSING_'))return `Eksik zorunlu kolon: ${code.slice(8)}.`;if(code.startsWith('ROW_'))return `CSV satır ${code.slice(4)} kolon sayısı başlıklarla uyuşmuyor.`;const map={EMPTY:'CSV boş.',CSV_INVALID:'CSV biçimi veya tırnak yapısı geçersiz.',HEADERS_INVALID:'Bilinmeyen, boş veya tekrarlı başlık var.',TOO_MANY:'Tek import en fazla 5.000 satır olabilir.',INVALID_FX_IMPORT_ROW:'FX satırlarından biri geçersiz.',INVALID_SETTLEMENT_DAY:'Settlement tarihi işlem tarihinden önce olamaz ve 370 günden fazla ileri olamaz.',NEGATIVE_IMPORT_VALUE:'Satış/iade/kesinti alanları negatif girilemez.',ECB_NETWORK:'ECB veri servisine ulaşılamadı.',ECB_SCHEMA_CHANGED:'ECB veri formatı beklenen şemayla eşleşmedi.',RATE_LIMITED:'Saatlik FX import sınırına ulaşıldı.'};return map[code]||code.startsWith('FX_RATE_MISSING_')?'İlgili tarih için ECB referans kuru bulunamadı.':map[code]||'FX import tamamlanamadı.'}
  function preview(){const root=document.getElementById('fxImportPreview');const sample=rows.slice(0,5),keys=['day','settlement_day','currency','external_product_id','gross_sales','commission_cost','seller_revenue'];root.innerHTML=`<table><thead><tr>${keys.map(key=>`<th>${key}</th>`).join('')}</tr></thead><tbody>${sample.map(row=>`<tr>${keys.map(key=>`<td>${escapeHtml(row[key]||'—')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;root.classList.remove('fx-import-hidden')}
  async function file(file){if(!file)return;if(file.size>MAX_FILE_BYTES){status('Dosya 2.5 MB sınırını aşıyor.','bad');return}try{const parsed=parse(await file.text());rows=parsed.rows;preview();document.getElementById('fxImportMeta').textContent=`${rows.length.toLocaleString('tr-TR')} satır · ${[...new Set(rows.map(row=>String(row.currency||'').toUpperCase()))].filter(Boolean).join(', ')}`;document.getElementById('fxImportBtn').disabled=false;status('Önizleme hazır. İçe aktarım yapılmadı; onay sonrası satırlar KârKalkan sunucusunda ECB referans oranıyla normalize edilir.','good')}catch(error){rows=[];document.getElementById('fxImportBtn').disabled=true;status(human(error),'bad')}}
  async function submit(){const id=connectionId();if(!id){status('Önce mağaza bağlantısı seç.','bad');return}if(!rows.length){status('Önce geçerli CSV seç.','bad');return}const fn=requestFn(),button=document.getElementById('fxImportBtn');if(!fn){status('Uygulama API katmanı hazır değil.','bad');return}button.disabled=true;button.textContent='ECB kurları doğrulanıyor…';status('Tarihsel referans kurlar alınıyor ve orijinal tutarlar audit kanıtına hazırlanıyor…');try{const result=await fn('marketplace-import-fx',{method:'POST',body:{connection_id:id,rows}}),fx=result?.fx||{};const variance=Number(fx.fxReferenceVarianceTry||0).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});status(`${Number(result.rows||rows.length).toLocaleString('tr-TR')} satır TRY bazına aktarıldı. Orijinal para kanıtı saklandı. Settlement referans FX farkı: ${variance}.`,'good')}catch(error){status(human(error),'bad')}finally{button.disabled=false;button.textContent='ECB kuru ile içe aktar'}}
  function template(){const text='day,settlement_day,currency,external_product_id,sku,product_name,sales_units,return_units,gross_sales,gross_returns,commission_cost,discount_cost,coupon_cost,seller_revenue\n2026-08-01,2026-08-05,EUR,SKU-1,SKU-1,Ornek Urun,2,0,199.90,0,24.50,0,0,175.40\n';const blob=new Blob([text],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='karkalkan-fx-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
  function init(){style();nav();shell();document.getElementById('fxImportFile')?.addEventListener('change',event=>void file(event.target.files?.[0]));document.getElementById('fxImportBtn')?.addEventListener('click',()=>void submit());document.getElementById('fxTemplateBtn')?.addEventListener('click',template)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
