'use strict';

const SUPABASE_URL='https://ilybqwjhkxfzociyvpeg.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_tix7qkJot2-3Hvik5kZvFg_SCYaZuzV';
const SESSION_KEY='karkalkan.v4.session';
const ACTIVE_CONNECTION_KEY='karkalkan.v4.activeConnection';
let session=null;

const byId=id=>document.getElementById(id);
const gateTrendyol=byId('gateTrendyol'),gateBilling=byId('gateBilling'),gateLegal=byId('gateLegal');
const gateTrendyolText=byId('gateTrendyolText'),gateBillingText=byId('gateBillingText'),gateLegalText=byId('gateLegalText');
const overall=byId('overallReadiness'),refreshButton=byId('refreshReadiness'),form=byId('reconciliationForm'),result=byId('reconciliationResult'),activeConnectionText=byId('activeConnectionText');

function readSession(){try{const value=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');return value&&typeof value.access_token==='string'&&typeof value.refresh_token==='string'?value:null}catch{return null}}
function saveSession(value){session=value;sessionStorage.setItem(SESSION_KEY,JSON.stringify(value))}
async function readJson(response){const text=await response.text();if(!text)return {};try{return JSON.parse(text)}catch{return {error:'INVALID_SERVER_RESPONSE'}}}
async function refreshSession(){if(!session?.refresh_token)throw new Error('UNAUTHORIZED');const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token}),cache:'no-store'});const data=await readJson(response);if(!response.ok)throw new Error('UNAUTHORIZED');const now=Math.floor(Date.now()/1000);saveSession({access_token:String(data.access_token||''),refresh_token:String(data.refresh_token||session.refresh_token),expires_at:Number(data.expires_at)||now+Number(data.expires_in||3600),user:data.user||session.user});return session.access_token}
async function token(){if(!session)throw new Error('UNAUTHORIZED');if(Number(session.expires_at||0)-Math.floor(Date.now()/1000)<90)return refreshSession();return session.access_token}
async function functionRequest(name,{method='GET',body}={}){let auth=await token();for(let attempt=0;attempt<2;attempt++){const response=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method,headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${auth}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await readJson(response);if(response.status===401&&attempt===0){auth=await refreshSession();continue}if(!response.ok)throw new Error(String(data?.error||`HTTP_${response.status}`));return data}throw new Error('UNAUTHORIZED')}
function markGate(card,ready,label){card?.classList.toggle('ready',ready);card?.classList.toggle('blocked',!ready);const chip=card?.querySelector('.gate-chip');if(chip)chip.textContent=label}
function render(data){const t=data.gates?.trendyol||{},b=data.gates?.billing||{},l=data.gates?.legal||{};markGate(gateTrendyol,!!t.ready,t.ready?'Hazır':'Bloklu');markGate(gateBilling,!!b.ready,b.ready?'Hazır':'Bloklu');markGate(gateLegal,!!l.ready,l.ready?'Hazır':'Bloklu');gateTrendyolText.textContent=t.ready?`Kapalı 7 günlük eşleşen mutabakat kaydı var (${t.latestMatchedPeriod?.start||''} → ${t.latestMatchedPeriod?.end||''}).`:`Bağlantı: ${t.connectionCount||0} · başarılı sync: ${t.successfulSync?'var':'yok'} · mutabakat: ${t.matchedReconciliation?'var':'yok'} · sıradaki: ${t.nextAction||'-'}`;gateBillingText.textContent=b.ready?'Production Paddle checkout → webhook → subscription kanıtı var.':`Config: ${b.configured?'hazır':'eksik'} · ortam: ${b.environment||'-'} · subscription webhook: ${b.subscriptionWebhookSeen?'var':'yok'} · canlı abonelik: ${b.liveSubscriptionSeen?'var':'yok'} · sıradaki: ${b.nextAction||'-'}`;gateLegalText.textContent=l.ready?'Operatör, başvuru kanalı ve hukuki onay tarihi yapılandırılmış.':`Operatör: ${l.operatorConfigured?'var':'eksik'} · başvuru kanalı: ${l.applicationChannelConfigured?'var':'eksik'} · onay: ${l.approvedAtConfigured?'var':'eksik'} · sıradaki: ${l.nextAction||'-'}`;overall.textContent=data.readyForAi?'Üç gate de kanıtlandı. AI sprintine geçiş için teknik launch gate açık.':'AI öncesi gate henüz kapalı. Yukarıdaki bloklu maddeler gerçek kanıt oluşmadan yeşile dönmez.'}
async function load(){refreshButton.disabled=true;try{render(await functionRequest('launch-readiness'))}catch(error){overall.textContent=error.message==='UNAUTHORIZED'?'Aktif oturum bulunamadı. Önce /uygulama üzerinden giriş yap.':'Hazırlık durumu okunamadı.'}finally{refreshButton.disabled=false}}
function activeConnection(){try{return sessionStorage.getItem(ACTIVE_CONNECTION_KEY)||''}catch{return ''}}
function showActiveConnection(){const id=activeConnection();activeConnectionText.textContent=id?`Aktif mağaza bağlantısı: ${id.slice(0,8)}… (yalnız oturumdaki bağlantı kullanılır)`:'Aktif mağaza seçili değil. Önce /uygulama içinde Trendyol mağazanı seç.';if(form)form.querySelector('button[type="submit"]').disabled=!id}
function totals(){const value={};document.querySelectorAll('[data-total]').forEach(input=>{value[input.dataset.total]=Number(input.value)});return value}
function formatReconciliation(data){const lines=[`Durum: ${data.status}`,`Dönem: ${data.period.start} → ${data.period.end}`,''];for(const [key,delta] of Object.entries(data.deltas||{}))lines.push(`${key}: fark ${Number(delta).toFixed(2)} TL`);return lines.join('\n')}

session=readSession();showActiveConnection();refreshButton?.addEventListener('click',load);form?.addEventListener('submit',async event=>{event.preventDefault();const connectionId=activeConnection();if(!connectionId)return;const button=byId('runReconciliation');button.disabled=true;result.hidden=false;result.className='reconciliation-result';result.textContent='Mutabakat hesaplanıyor…';try{const data=await functionRequest('trendyol-reconciliation',{method:'POST',body:{connection_id:connectionId,period_start:byId('periodStart').value,period_end:byId('periodEnd').value,source_totals:totals()}});result.textContent=formatReconciliation(data);result.classList.add(data.matched?'good':'bad');await load()}catch(error){result.textContent=`Mutabakat tamamlanamadı: ${error.message}`;result.classList.add('bad')}finally{button.disabled=false}});load();
