'use strict';

/* KârKalkan seller dashboard enhancement layer.
 * One script owns vNext rendering, live signals, evidence confidence,
 * operating expenses and portfolio refreshes.
 */
const kkState={
  mounted:false,
  liveTimer:null,
  decision:null,
  evidence:{sales:null,returns:null,cost:null,cargo:null}
};
const kkCategoryLabels={ads:'Reklam',packaging:'Paketleme',rent:'Kira',payroll:'Personel',software:'Yazılım / araçlar',other:'Diğer'};

function kkClamp(value,min=0,max=1){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):0}
function kkHasNumber(value){return value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))}
function kkMoney(value,currency='TRY'){if(!kkHasNumber(value))return'—';const n=Number(value);try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency,maximumFractionDigits:0}).format(n)}catch{return`${Math.round(n).toLocaleString('tr-TR')} ${currency}`}}
function kkEsc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function kkDateLabel(value){const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleDateString('tr-TR',{day:'2-digit',month:'short'})}
function kkIstanbulDay(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=type=>parts.find(part=>part.type===type)?.value||'';return`${get('year')}-${get('month')}-${get('day')}`}
function kkMonthStart(){return`${kkIstanbulDay().slice(0,7)}-01`}

function kkMount(){
  if(kkState.mounted)return true;
  const dashboard=document.getElementById('dashboard');
  const syncMessage=document.getElementById('syncMessage');
  if(!dashboard||!syncMessage)return false;
  kkState.mounted=true;

  const oldTrend=document.getElementById('trendPanel');if(oldTrend)oldTrend.hidden=true;
  const oldTruth=document.getElementById('financeTruthPanel');
  if(oldTruth){const eyebrow=oldTruth.querySelector('.eyebrow'),title=oldTruth.querySelector('h3');if(eyebrow)eyebrow.textContent='HAKEDİŞ VE KESİNTİLER';if(title)title.textContent='Doğrulanmış finans kalemleri'}
  document.querySelector('.v4-topbar .eyebrow')?.replaceChildren(document.createTextNode('KÂRKALKAN · PARA AKIŞI'));
  const topTitle=document.querySelector('.v4-topbar h1');if(topTitle)topTitle.textContent='Paranın nerede kaldığını gör';
  const sideStatus=document.querySelector('.side-status small');if(sideStatus)sideStatus.textContent='Hızlı sinyal · doğrulanmış finans';

  kkMountNavigation();
  kkMountDashboardCards(syncMessage);
  kkMountOperations();
  document.getElementById('kkWebhookBtn')?.addEventListener('click',kkRegisterWebhook);
  document.getElementById('kkExpenseSave')?.addEventListener('click',kkSaveExpense);
  const expenseStart=document.getElementById('kkExpenseStart');if(expenseStart)expenseStart.value=kkMonthStart();
  const expenseEnd=document.getElementById('kkExpenseEnd');if(expenseEnd)expenseEnd.value=kkIstanbulDay();
  return true;
}

function kkMountNavigation(){
  const nav=document.querySelector('.side-nav');if(!nav)return;
  const baseNames=['Genel Bakış','Mağaza Bağlantısı','Güvenli Bağlantı','Ürün Maliyetleri','Veri Geçmişi'];
  [...nav.querySelectorAll('a')].slice(0,5).forEach((link,index)=>{link.innerHTML=`<span>${String(index+1).padStart(2,'0')}</span> ${baseNames[index]}`});
  const extras=[['#kkLiveStream','06','Canlı Siparişler'],['#kkFlowCard','07','Para Akışı'],['#kkOperatingExpenses','08','İşletme Giderleri'],['#kkPortfolio','09','Mağaza Portföyü']];
  for(const[href,no,label]of extras){if(nav.querySelector(`a[href="${href}"]`))continue;const link=document.createElement('a');link.href=href;link.innerHTML=`<span>${no}</span> ${label}`;nav.append(link)}
  const links=[...nav.querySelectorAll('a')];
  const setActive=()=>{let best=null,bestTop=Infinity;for(const link of links){const target=document.querySelector(link.getAttribute('href'));if(!target)continue;const top=Math.abs(target.getBoundingClientRect().top-120);if(top<bestTop){best=link;bestTop=top}}links.forEach(link=>link.classList.toggle('is-active',link===best))};
  window.addEventListener('scroll',setActive,{passive:true});setActive();
}

function kkMountDashboardCards(syncMessage){
  const command=document.createElement('div');command.className='kk-command-bar';command.innerHTML=`<article class="kk-command-main"><div class="kk-kicker">KârKalkan yaklaşımı</div><h3 class="kk-command-title">Hızlı sipariş sinyali, sonradan doğrulanan finans gerçeği.</h3><p class="kk-command-copy">Sipariş geldiğinde erken sinyal al; hakediş, kargo ve maliyet verisi geldikçe rakamın hangi bölümünün gerçekten doğrulandığını ayrı gör.</p><div class="kk-command-tags"><span>Satış kanıtı</span><span>İade kanıtı</span><span>Maliyet kapsamı</span><span>Kargo eşleşmesi</span><span>Hakediş düzeltmeleri</span></div></article><article class="kk-live-card"><div class="kk-live-head"><div><strong>Canlı sipariş sinyali</strong><small>Webhook hızlı haberdar eder; periyodik senkron finansı doğrular.</small></div><span id="kkWebhookState" class="kk-live-state"><i></i> Kontrol ediliyor</span></div><div class="kk-live-actions"><button id="kkWebhookBtn" class="btn ghost compact-btn" type="button">Canlı akışı kur</button><span id="kkWebhookMessage" class="kk-live-note">Önce mağaza ve API bilgileri gerekir.</span></div></article>`;syncMessage.after(command);

  const insight=document.createElement('div');insight.className='kk-insight-grid';insight.innerHTML=`<article class="kk-chart-card"><div class="kk-card-head"><div><div class="kk-kicker">Günlük görünüm</div><h3>Satış ve bilinen nakit akışı</h3><p>Satış hacmi ile platform/kargo kesintileri ve stopaj sonrası bilinen nakdi gün gün birlikte oku.</p></div><span class="kk-card-badge">Grafik</span></div><div id="kkDailyChart" class="kk-chart-wrap"><div class="kk-chart-empty">Veri bekleniyor.</div></div><div class="kk-chart-legend"><span class="sales"><i></i>Toplam satış</span><span class="cash"><i></i>Stopaj dahil bilinen nakit</span></div></article><article class="kk-evidence-card"><div class="kk-card-head"><div><div class="kk-kicker">Finansal veri güveni</div><h3 id="kkHealthTitle">Rakamın dayanağı</h3><p>Puan, mağazanın başarısını değil finans verisinin ne kadar kanıtlı ve eksiksiz olduğunu gösterir.</p></div><span id="kkHealthBadge" class="kk-card-badge">Veri güveni</span></div><div id="kkEvidenceList" class="kk-evidence-list"></div><div class="kk-evidence-callout">KârKalkan emin olmadığı kısmı saklamaz. Ölçülemeyen bileşen skora zorla eklenmez.</div></article>`;
  const health=document.querySelector('#dashboard .health-grid');(health||command).after(insight);

  const flow=document.createElement('article');flow.id='kkFlowCard';flow.className='kk-flow-card';flow.innerHTML=`<div class="kk-card-head"><div><div class="kk-kicker">Para köprüsü</div><h3>Satıştan bilinen nakde</h3><p>Kesintilerin etkisini tek bakışta gör. Bu görünüm muhasebe net kârı değildir.</p></div><span class="kk-card-badge">Açıklanabilir finans</span></div><div id="kkFlowGrid" class="kk-flow-grid"><div class="kk-chart-empty" style="grid-column:1/-1">Veri bekleniyor.</div></div>`;
  const kpis=document.querySelector('#dashboard .v4-kpis');(kpis||insight).after(flow);

  const radar=document.createElement('article');radar.id='kkLeakRadar';radar.className='kk-live-stream';radar.innerHTML=`<div class="kk-card-head"><div><div class="kk-kicker">Para kaçağı radarı</div><h3>Önce kontrol etmen gereken yerler</h3><p>Kesin zarar iddiası değil; finans sonucunu bozabilecek kanıt boşlukları ve sıra dışı hareketler.</p></div><span class="kk-card-badge">Açıklanabilir</span></div><div id="kkLeakList" class="kk-live-list"><div class="kk-live-empty">Radar için doğrulanmış veri bekleniyor.</div></div>`;flow.after(radar);
  const live=document.createElement('article');live.id='kkLiveStream';live.className='kk-live-stream';live.innerHTML=`<div class="kk-card-head"><div><div class="kk-kicker">Canlı akış</div><h3>Son sipariş sinyalleri</h3><p>Webhook durum değişikliklerini hızlı gösterir; finansal tutar daha sonra hakedişle doğrulanır.</p></div><span class="kk-card-badge">Minimum veri</span></div><div id="kkLiveList" class="kk-live-list"><div class="kk-live-empty">Canlı sipariş akışı henüz kurulmadı.</div></div>`;radar.after(live);
}

function kkMountOperations(){
  const anchor=document.getElementById('kkLiveStream');if(!anchor)return;
  const grid=document.createElement('div');grid.className='kk-ops-grid';grid.innerHTML=`<article id="kkOperatingExpenses" class="kk-ops-card"><div class="kk-card-head"><div><div class="kk-kicker">İşletme giderleri</div><h3>Ürün maliyetinden ayrı tut</h3><p>Reklam, kira, personel ve araç giderlerini döneme göre ekle.</p></div><span class="kk-card-badge">Gider defteri</span></div><div class="kk-ops-body"><div class="kk-ops-form"><div class="field"><label for="kkExpenseCategory">Tür</label><select id="kkExpenseCategory"><option value="ads">Reklam</option><option value="packaging">Paketleme</option><option value="rent">Kira</option><option value="payroll">Personel</option><option value="software">Yazılım / araçlar</option><option value="other">Diğer</option></select></div><div class="field span-2"><label for="kkExpenseLabel">Açıklama</label><input class="input" id="kkExpenseLabel" maxlength="120" placeholder="Örn. Ağustos reklam bütçesi"></div><div class="field"><label for="kkExpenseAmount">Tutar (₺)</label><input class="input" id="kkExpenseAmount" inputmode="decimal" placeholder="2500"></div><div class="field"><label for="kkExpenseStart">Başlangıç</label><input class="input" id="kkExpenseStart" type="date"></div><div class="field"><label for="kkExpenseEnd">Bitiş</label><input class="input" id="kkExpenseEnd" type="date"></div><div class="kk-ops-actions span-2"><button id="kkExpenseSave" class="btn primary" type="button">Gideri kaydet</button></div></div><p id="kkExpenseMessage" class="kk-ops-note">Giderler seçili tarih aralığına paylaştırılır; resmî muhasebe kaydı değildir.</p><div id="kkExpenseList" class="kk-expense-list"><div class="kk-empty-box">Giderler yükleniyor.</div></div></div></article><article id="kkPortfolio" class="kk-portfolio-card"><div class="kk-card-head"><div><div class="kk-kicker">Mağaza portföyü</div><h3>Tüm mağazaların tek finans görünümü</h3><p>Bilinen nakit ile maliyet kapsamını ayrı gör. Maliyet eksikse katkı sonucu sayı uydurmaz.</p></div><span id="kkPortfolioBadge" class="kk-card-badge">Portföy</span></div><div id="kkPortfolioSummary" class="kk-portfolio-summary"><div class="kk-empty-box" style="grid-column:1/-1">Portföy yükleniyor.</div></div><div id="kkStoreList" class="kk-store-list"></div></article>`;
  anchor.after(grid);
}

function kkRenderEvidence(){
  const host=document.getElementById('kkEvidenceList');if(!host)return;
  const components=Array.isArray(kkState.decision?.components)?kkState.decision.components:[];
  if(components.length){const score=Number(kkState.decision?.confidenceScore??kkState.decision?.healthScore??0),label=kkState.decision?.confidenceLabel||kkState.decision?.healthLabel||'Değerlendiriliyor';const title=document.getElementById('kkHealthTitle');if(title)title.textContent=`${score}/100 · ${label}`;host.innerHTML=components.map(component=>{const applicable=component?.applicable!==false&&kkHasNumber(component?.score),value=applicable?Math.max(0,Math.min(100,Number(component.score))):0;return`<div class="kk-evidence-row"><header><span>${kkEsc(component.label)}</span><strong>${applicable?`%${value}`:'Bu dönemde ölçülmedi'}</strong></header><div class="kk-meter"><i style="width:${value}%"></i></div><small>${kkEsc(component.help)}${applicable?` · Temel ağırlık %${Number(component.weight)||0}`:' · Skora katılmadı'}</small></div>`}).join('');return}
  const rows=[['Satış kanıtı',kkState.evidence.sales,'Satış hacminin sipariş satırlarıyla doğrulanabilen bölümü.'],['İade kanıtı',kkState.evidence.returns,'Ölçülebilir iadelerin claim kayıtlarıyla doğrulanabilen bölümü.'],['Ürün maliyeti kapsamı',kkState.evidence.cost,'Maliyeti bilinen satış hacmi.'],['Kargo eşleşmesi',kkState.evidence.cargo,'Kargo faturasının ürüne kanıtlı dağıtılabilen bölümü.']];host.innerHTML=rows.map(([label,value,help])=>{const ready=kkHasNumber(value),pct=ready?Math.round(kkClamp(value)*100):0;return`<div class="kk-evidence-row"><header><span>${label}</span><strong>${ready?`%${pct}`:'—'}</strong></header><div class="kk-meter"><i style="width:${pct}%"></i></div><small>${help}</small></div>`}).join('')
}

function kkRenderDaily(data){const host=document.getElementById('kkDailyChart');if(!host)return;const rows=Array.isArray(data?.daily)?data.daily.filter(row=>row?.day):[];if(rows.length<2){host.innerHTML='<div class="kk-chart-empty">Grafik için en az iki günlük veri gerekir.</div>';return}const W=720,H=250,L=42,R=12,T=16,B=34,plotW=W-L-R,plotH=H-T-B,cashOf=row=>Number(row.knownCashAfterFeesAndStoppage??row.knownFeeNet??row.adjustedSellerRevenue??row.sellerRevenue)||0,values=rows.flatMap(row=>[Number(row.grossSales)||0,cashOf(row)]),max=Math.max(1,...values),min=Math.min(0,...values),range=Math.max(1,max-min),x=index=>L+index*plotW/(rows.length-1),y=value=>T+(max-(Number(value)||0))*plotH/range,sales=rows.map((row,index)=>`${x(index).toFixed(1)},${y(row.grossSales).toFixed(1)}`).join(' '),cash=rows.map((row,index)=>`${x(index).toFixed(1)},${y(cashOf(row)).toFixed(1)}`).join(' '),grid=[0,.25,.5,.75,1].map(step=>{const gy=T+step*plotH,val=max-step*range;return`<line class="kk-grid-line" x1="${L}" y1="${gy}" x2="${L+plotW}" y2="${gy}"/><text class="kk-axis-label" x="${L-7}" y="${gy+3}" text-anchor="end">${Math.round(val/1000)}k</text>`}).join(''),labelStep=Math.max(1,Math.ceil(rows.length/6)),labels=rows.map((row,index)=>index%labelStep===0||index===rows.length-1?`<text class="kk-axis-label" x="${x(index)}" y="${H-10}" text-anchor="middle">${kkDateLabel(row.day)}</text>`:'').join('');host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Günlük satış ve stopaj dahil bilinen nakit grafiği">${grid}<polyline class="kk-sales-line" points="${sales}"/><polyline class="kk-cash-line" points="${cash}"/>${labels}</svg>`}

function kkRenderFlow(data){const host=document.getElementById('kkFlowGrid');if(!host)return;const t=data?.totals||{},s=data?.settlementSnapshot||{},o=data?.otherFinancialSnapshot||{},final=Number(o.knownCashAfterFeesAndStoppage??t.knownCashAfterFeesAndStoppage??o.knownFeeNet??t.knownFeeNet??0),items=[['Toplam satış',Number(t.grossSales)||0,'base'],['İade',Math.abs(Number(t.grossReturns)||0),'negative'],['Komisyon',Math.abs(Number(t.commissionCost)||0),'negative'],['Hakediş düzeltmesi',Math.abs(Number(s.adjustmentNet??t.settlementAdjustmentNet)||0),'adjustment'],['Platform ücreti',Math.abs(Number(o.platformServiceFeeCost??t.platformServiceFeeCost)||0),'negative'],['Kargo',Math.abs(Number(o.cargoCost??t.cargoCost)||0),'negative'],['Stopaj',Math.abs(Number(o.stoppageNet??t.stoppageNet)||0),'negative'],['Bilinen nakit',final,'final']],max=Math.max(1,...items.map(item=>Math.abs(Number(item[1])||0)));host.innerHTML=items.map(([label,value,kind])=>`<div class="kk-flow-item ${kind}"><div class="kk-flow-bar-shell"><div class="kk-flow-bar" style="height:${Math.max(3,Math.round(Math.abs(Number(value)||0)/max*100))}%"></div></div><span>${kkEsc(label)}</span><strong>${kkMoney(value)}</strong></div>`).join('')}
function kkRenderDashboard(data){const unit=data?.unitSnapshot||{};kkState.evidence.sales=kkHasNumber(unit.salesEvidenceCoverage)?kkClamp(unit.salesEvidenceCoverage):null;kkState.evidence.returns=unit.returnEvidenceApplicable===false?null:kkHasNumber(unit.returnEvidenceCoverage)?kkClamp(unit.returnEvidenceCoverage):null;kkState.evidence.cost=kkHasNumber(data?.salesCostCoverage)?kkClamp(data.salesCostCoverage):kkHasNumber(data?.costCoverage)?kkClamp(data.costCoverage):null;kkRenderEvidence();kkRenderDaily(data);kkRenderFlow(data)}
function kkRenderRadar(data){const host=document.getElementById('kkLeakList');if(!host)return;const rows=Array.isArray(data?.moneyLeakRadar)?data.moneyLeakRadar:[];if(!rows.length){host.innerHTML='<div class="kk-live-empty">Belirgin veri boşluğu görünmüyor. Bu, muhasebe açısından kesin sorun olmadığı anlamına gelmez.</div>';return}host.innerHTML=rows.map(row=>`<div class="kk-live-row"><strong>${kkEsc(row.title)}</strong><span class="kk-status">${row.severity==='high'?'Öncelikli':'Kontrol et'}</span><span>${row.impactBasis==null?'Tutar belirtilmedi':`Etkilenen taban ${kkMoney(row.impactBasis)}`}</span><span title="${kkEsc(row.message)}">${kkEsc(row.message)}</span></div>`).join('')}

async function kkLoadDecision(){if(!activeConnectionId){kkState.decision=null;kkRenderEvidence();kkRenderRadar(null);return}try{const days=Number(els?.rangeDays?.value||30),data=await functionRequest('decision-center',{query:{connection_id:activeConnectionId,days}});kkState.decision=data;kkRenderEvidence();kkRenderRadar(data)}catch{kkState.decision=null;kkRenderEvidence();const host=document.getElementById('kkLeakList');if(host)host.innerHTML='<div class="kk-live-empty">Veri güveni ve radar şu an okunamadı.</div>'}}
async function kkLoadWebhookState(){const badge=document.getElementById('kkWebhookState'),button=document.getElementById('kkWebhookBtn'),message=document.getElementById('kkWebhookMessage');if(!badge||!button||!message)return;if(!activeConnectionId){badge.className='kk-live-state';badge.innerHTML='<i></i> Mağaza seç';button.disabled=true;message.textContent='Önce mağaza seç.';return}button.disabled=false;try{const data=await functionRequest('webhook-manager',{query:{connection_id:activeConnectionId}});if(data?.active&&data?.providerVerified){badge.className='kk-live-state ready';badge.innerHTML='<i></i> Trendyol’da aktif';button.textContent='Doğrula ve anahtarı yenile';message.textContent='Webhook Trendyol tarafında ACTIVE olarak doğrulandı.'}else if(data?.configured){badge.className='kk-live-state warn';badge.innerHTML=`<i></i> ${kkEsc(data?.providerStatus||'Onarım gerekli')}`;button.textContent='Canlı akışı onar';message.textContent='Yerel kayıt var ancak sağlayıcı tarafı aktif değil.'}else{badge.className='kk-live-state warn';badge.innerHTML='<i></i> Kurulu değil';button.textContent='Canlı akışı kur';message.textContent='Mağazanın API bilgileriyle webhook aboneliği açılır.'}}catch{badge.className='kk-live-state';badge.innerHTML='<i></i> Doğrulanamadı';button.textContent='Tekrar doğrula';message.textContent='Trendyol webhook durumu şu an doğrulanamadı.'}}
async function kkRegisterWebhook(){const button=document.getElementById('kkWebhookBtn'),message=document.getElementById('kkWebhookMessage');if(!button||!message||!activeConnectionId)return;button.disabled=true;button.textContent='Doğrulanıyor…';try{const data=await functionRequest('webhook-manager',{method:'POST',body:{connection_id:activeConnectionId}});message.textContent=data?.active?'Canlı sipariş bağlantısı Trendyol tarafında doğrulandı.':'Bağlantı doğrulanamadı.';await Promise.allSettled([kkLoadWebhookState(),kkLoadLiveOrders(),kkLoadDecision()])}catch(error){message.textContent=humanError(error)}finally{button.disabled=false}}
async function kkLoadLiveOrders(){const host=document.getElementById('kkLiveList');if(!host)return;if(!activeConnectionId){host.innerHTML='<div class="kk-live-empty">Canlı akış için mağaza seç.</div>';return}try{const data=await functionRequest('live-overview',{query:{connection_id:activeConnectionId}}),rows=Array.isArray(data?.liveOrders?.rows)?data.liveOrders.rows.slice(0,8):[];if(!rows.length){host.innerHTML='<div class="kk-live-empty">Henüz gerçek webhook sipariş sinyali yok.</div>';return}host.innerHTML=rows.map(row=>`<div class="kk-live-row"><strong>#${kkEsc(row.order_number||row.package_id||'—')}</strong><span class="kk-status">${kkEsc(row.status||'Bilinmiyor')}</span><span>${kkHasNumber(row.total_amount)?kkMoney(row.total_amount):'Tutar bekleniyor'}</span><span>${row.event_at?new Date(row.event_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}):'—'}</span></div>`).join('')}catch{host.innerHTML='<div class="kk-live-empty">Canlı siparişler şu an okunamadı.</div>'}}

async function kkLoadExpenses(){const host=document.getElementById('kkExpenseList');if(!host)return;if(!activeConnectionId){host.innerHTML='<div class="kk-empty-box">Önce mağaza seç.</div>';return}try{const data=await functionRequest('operating-expenses',{query:{connection_id:activeConnectionId}}),rows=Array.isArray(data?.expenses)?data.expenses:[];if(!rows.length){host.innerHTML='<div class="kk-empty-box">Henüz işletme gideri yok.</div>';return}host.innerHTML=rows.map(row=>`<div class="kk-expense-row"><div><strong>${kkEsc(row.label)}</strong><small>${kkEsc(kkCategoryLabels[row.category]||row.category)}</small></div><span>${kkMoney(row.amount)}</span><small>${kkEsc(row.period_start)} → ${kkEsc(row.period_end)}</small><button class="kk-expense-delete" type="button" data-expense-id="${kkEsc(row.id)}">Sil</button></div>`).join('');host.querySelectorAll('[data-expense-id]').forEach(button=>button.addEventListener('click',()=>kkDeleteExpense(button.dataset.expenseId)))}catch(error){host.innerHTML=`<div class="kk-empty-box">Giderler alınamadı: ${kkEsc(humanError(error))}</div>`}}
async function kkSaveExpense(){const button=document.getElementById('kkExpenseSave'),message=document.getElementById('kkExpenseMessage');if(!button||!message||!activeConnectionId){if(message)message.textContent='Önce mağaza seç.';return}const category=document.getElementById('kkExpenseCategory').value,label=String(document.getElementById('kkExpenseLabel').value||'').trim(),amount=Number(String(document.getElementById('kkExpenseAmount').value||'').replace(',','.')),period_start=document.getElementById('kkExpenseStart').value,period_end=document.getElementById('kkExpenseEnd').value;if(!label||!Number.isFinite(amount)||amount<=0||!period_start||!period_end||period_end<period_start){message.textContent='Açıklama, sıfırdan büyük tutar ve geçerli tarih aralığı gir.';return}button.disabled=true;button.textContent='Kaydediliyor…';try{await functionRequest('operating-expenses',{method:'POST',body:{action:'create',connection_id:activeConnectionId,category,label,amount,period_start,period_end}});document.getElementById('kkExpenseLabel').value='';document.getElementById('kkExpenseAmount').value='';message.textContent='Gider kaydedildi.';await Promise.allSettled([kkLoadExpenses(),kkLoadPortfolio()])}catch(error){message.textContent=humanError(error)}finally{button.disabled=false;button.textContent='Gideri kaydet'}}
async function kkDeleteExpense(id){if(!activeConnectionId||!id)return;try{await functionRequest('operating-expenses',{method:'POST',body:{action:'delete',connection_id:activeConnectionId,id}});await Promise.allSettled([kkLoadExpenses(),kkLoadPortfolio()])}catch(error){const message=document.getElementById('kkExpenseMessage');if(message)message.textContent=humanError(error)}}
async function kkLoadPortfolio(){const summary=document.getElementById('kkPortfolioSummary'),list=document.getElementById('kkStoreList'),badge=document.getElementById('kkPortfolioBadge');if(!summary||!list||!badge)return;try{const days=Number(els?.rangeDays?.value||30),data=await functionRequest('portfolio-summary',{query:{days}}),totals=data?.totals||{},stores=Array.isArray(data?.stores)?data.stores:[],coverage=kkHasNumber(totals.costCoverage)?Math.round(Number(totals.costCoverage)*100):0,known=kkHasNumber(totals.operatingContribution);badge.textContent=`${Number(data?.storeCount||0)} mağaza`;summary.innerHTML=`<div class="kk-portfolio-kpi"><span>Toplam satış</span><strong>${kkMoney(totals.grossSales)}</strong><small>${days} günlük portföy</small></div><div class="kk-portfolio-kpi"><span>Stopaj dahil bilinen nakit</span><strong>${kkMoney(totals.knownCashAfterFeesAndStoppage)}</strong><small>Ürün maliyeti henüz düşülmemiştir</small></div><div class="kk-portfolio-kpi"><span>Maliyet kapsamı</span><strong>%${coverage}</strong><small>${coverage>=100?'Katkı hesabı için tamam':'Eksik maliyet sonucu belirsiz bırakır'}</small></div><div class="kk-portfolio-kpi"><span>Maliyet + gider sonrası katkı</span><strong>${known?kkMoney(totals.operatingContribution):'Bilinmiyor'}</strong><small>${known?'Muhasebe net kârı değildir':'Maliyet kapsamı tamamlanmadan hesaplanmaz'}</small></div>`;list.innerHTML=stores.length?stores.map(store=>{const cov=kkHasNumber(store.costCoverage)?Math.round(Number(store.costCoverage)*100):0,knownContribution=kkHasNumber(store.operatingContribution);return`<div class="kk-store-row ${store.id===activeConnectionId?'active':''}"><div class="name"><strong>${kkEsc(store.displayName||'Mağaza')}</strong><small>${kkEsc(String(store.marketplace||'').toLocaleUpperCase('tr-TR'))} · ${kkEsc(store.sellerId||'—')}</small></div><div class="kk-store-cell"><span>Satış</span><strong>${kkMoney(store.grossSales)}</strong></div><div class="kk-store-cell"><span>Bilinen nakit</span><strong>${kkMoney(store.knownCashAfterFeesAndStoppage)}</strong></div><div class="kk-store-cell"><span>Maliyet kapsamı</span><strong>%${cov}</strong></div><div class="kk-store-cell"><span>Katkı</span><strong>${knownContribution?kkMoney(store.operatingContribution):'Bilinmiyor'}</strong></div></div>`}).join(''):'<div class="kk-empty-box">Henüz mağaza yok.</div>'}catch(error){summary.innerHTML=`<div class="kk-empty-box" style="grid-column:1/-1">Portföy alınamadı: ${kkEsc(humanError(error))}</div>`;list.innerHTML=''}}

async function kkRefreshAuxiliary(){await Promise.allSettled([kkLoadWebhookState(),kkLoadLiveOrders(),kkLoadDecision(),kkLoadExpenses(),kkLoadPortfolio()])}
function kkResetAuxiliary(){kkState.evidence={sales:null,returns:null,cost:null,cargo:null};kkState.decision=null;kkRenderEvidence();kkRenderRadar(null);const chart=document.getElementById('kkDailyChart');if(chart)chart.innerHTML='<div class="kk-chart-empty">Veri bekleniyor.</div>';const flow=document.getElementById('kkFlowGrid');if(flow)flow.innerHTML='<div class="kk-chart-empty" style="grid-column:1/-1">Veri bekleniyor.</div>'}
function kkStartLivePolling(){if(kkState.liveTimer)clearInterval(kkState.liveTimer);kkState.liveTimer=setInterval(()=>{if(activeConnectionId&&!document.hidden)kkLoadLiveOrders().catch(()=>{})},12000)}

function kkBoot(){if(!kkMount()){setTimeout(kkBoot,120);return}kkRenderEvidence();kkStartLivePolling();kkRefreshAuxiliary().catch(()=>{})}

if(typeof renderDashboard==='function'){const coreRenderDashboard=renderDashboard;renderDashboard=function(data){coreRenderDashboard(data);kkRenderDashboard(data)}}
if(typeof alertRender==='function'){const coreAlertRender=alertRender;alertRender=function(data){coreAlertRender(data);const coverage=data?.financialTruth?.cargoAllocationCoverage;kkState.evidence.cargo=kkHasNumber(coverage)?kkClamp(Number(coverage)/100):null;kkRenderEvidence()}}
if(typeof refreshConnectionData==='function'){const coreRefresh=refreshConnectionData;refreshConnectionData=async function(){await coreRefresh();await kkRefreshAuxiliary()}}
if(typeof resetDashboardOnly==='function'){const coreReset=resetDashboardOnly;resetDashboardOnly=function(){coreReset();kkResetAuxiliary();kkLoadWebhookState().catch(()=>{});kkLoadLiveOrders().catch(()=>{})}}

kkBoot();
