'use strict';

(() => {
  const SECTION_ID='weeklyFinance';
  const STYLE_ID='karkalkan-weekly-finance-style';

  function addStyle(){if(document.getElementById(STYLE_ID))return;const link=document.createElement('link');link.id=STYLE_ID;link.rel='stylesheet';link.href='/weekly-finance.css?v=20260821';document.head.appendChild(link)}
  function requestFn(){if(typeof globalThis.functionRequest==='function')return globalThis.functionRequest;try{if(typeof functionRequest==='function')return functionRequest}catch{}return null}
  function connectionId(){return String(document.getElementById('connectionSelect')?.value||'').trim()}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function money(value,currency='TRY'){const n=Number(value);if(!Number.isFinite(n))return '—';try{return n.toLocaleString('tr-TR',{style:'currency',currency})}catch{return `${n.toLocaleString('tr-TR')} ${currency}`}}
  function pct(value){const n=Number(value);return Number.isFinite(n)?`${n>0?'+':''}${n.toLocaleString('tr-TR',{maximumFractionDigits:2})}%`:'—'}
  function status(message,kind=''){const el=document.getElementById('weeklyFinanceStatus');if(!el)return;el.textContent=message;el.className=`weekly-finance-status${kind?` ${kind}`:''}`}
  function addNav(){const nav=document.querySelector('.side-nav');if(!nav||nav.querySelector('a[href="#weeklyFinance"]'))return;const anchor=nav.querySelector('a[href="#financeAi"]')||nav.querySelector('a[href="#dashboard"]');const link=document.createElement('a');link.href='#weeklyFinance';link.innerHTML='<span>7G</span> Haftalık özet';anchor?.insertAdjacentElement('afterend',link)}
  function shell(){if(document.getElementById(SECTION_ID))return;const anchor=document.getElementById('financeAi')||document.getElementById('dashboard');if(!anchor)return;const section=document.createElement('section');section.id=SECTION_ID;section.className='section weekly-finance-section';section.innerHTML=`<div class="weekly-finance-shell"><div class="weekly-finance-head"><div><p class="eyebrow">KAPALI 7 GÜN · DETERMINISTIC</p><h2>Bu hafta ne değişti?</h2><p>Son tamamlanmış 7 takvim gününü önceki 7 günle karşılaştırır. Finans rakamlarını AI hesaplamaz; maliyet kapsamı eksikse katkı sonucu kesinleştirilmez.</p></div><button id="weeklyFinanceRefresh" type="button">Özeti yenile</button></div><div id="weeklyFinanceStatus" class="weekly-finance-status">Mağaza seçimi bekleniyor.</div><div id="weeklyFinanceBody" class="weekly-finance-body weekly-finance-hidden"></div><p class="weekly-finance-note">Bu ekran içi özet otomatik e-posta gönderildiği anlamına gelmez. E-posta teslimi ayrıca yapılandırılmalı ve doğrulanmalıdır.</p></div>`;anchor.insertAdjacentElement('afterend',section)}
  function metric(label,current,previous,format,change){return `<div class="weekly-finance-metric"><span>${escapeHtml(label)}</span><strong>${escapeHtml(format(current))}</strong><small>Önceki: ${escapeHtml(format(previous))}${change===undefined?'':` · ${escapeHtml(pct(change))}`}</small></div>`}
  function render(result){const current=result?.current||{},previous=result?.previous||{},change=result?.change||{},currency=current.currency||'TRY',body=document.getElementById('weeklyFinanceBody');if(!body)return;const contributionCurrent=current.contributionAfterKnownCosts,contributionPrevious=previous.contributionAfterKnownCosts;const signals=Array.isArray(result?.signals)?result.signals:[];body.innerHTML=`<div class="weekly-finance-range"><strong>${escapeHtml(current.start||'—')} → ${escapeHtml(current.end||'—')}</strong><span>Önceki dönem: ${escapeHtml(previous.start||'—')} → ${escapeHtml(previous.end||'—')}</span></div><div class="weekly-finance-grid">${metric('Brüt satış',current.grossSales,previous.grossSales,v=>money(v,currency),change.grossSalesPercent)}${metric('Bilinen kesintiler sonrası nakit',current.knownCashAfterFeesAndStoppage,previous.knownCashAfterFeesAndStoppage,v=>money(v,currency),change.knownCashPercent)}${metric('İade oranı',current.returnRate,previous.returnRate,v=>`${Number(v||0).toLocaleString('tr-TR',{maximumFractionDigits:2})}%`,undefined)}${metric('Bilinen maliyetler sonrası katkı',contributionCurrent,contributionPrevious,v=>v===null?'Maliyet kapsamı eksik':money(v,currency),change.contributionPercent)}</div><div class="weekly-finance-coverage"><span>Satış bazlı maliyet kapsamı <strong>%${escapeHtml((Number(current.costCoverage||0)*100).toLocaleString('tr-TR',{maximumFractionDigits:1}))}</strong></span><span>Other Financials <strong>${escapeHtml(current.otherFinancialCoverage||'none')}</strong></span><span>İşlem <strong>${escapeHtml(Number(current.transactions||0).toLocaleString('tr-TR'))}</strong></span></div><div class="weekly-finance-signals">${signals.map(item=>`<div class="weekly-finance-signal ${item.severity==='watch'?'watch':item.severity==='good'?'good':''}"><strong>${escapeHtml(item.code||'SINYAL')}</strong><span>${escapeHtml(item.text||'')}</span></div>`).join('')}</div>`;body.classList.remove('weekly-finance-hidden');status(`Özet ${new Date(result.generatedAt||Date.now()).toLocaleString('tr-TR')} tarihinde üretildi. Finans matematiği deterministic.`, 'good')}
  async function load(){const id=connectionId();const body=document.getElementById('weeklyFinanceBody');if(!id){body?.classList.add('weekly-finance-hidden');status('Önce bir mağaza bağlantısı seç.');return}const fn=requestFn();if(!fn){status('Uygulama API katmanı hazır değil.','bad');return}const button=document.getElementById('weeklyFinanceRefresh');if(button)button.disabled=true;status('Son iki kapalı 7 günlük dönem hesaplanıyor…');try{render(await fn('weekly-finance-summary',{method:'GET',query:{connection_id:id}}))}catch(error){const code=String(error?.message||'');const map={RATE_LIMITED:'Haftalık özet kullanım sınırına ulaştı.',DATA_TOO_LARGE:'Özet için veri hacmi sınırı aşıldı; daha büyük sync mimarisi gerekli.',NOT_FOUND:'Seçili mağazaya erişilemiyor.'};status(map[code]||'Haftalık özet şu anda üretilemedi.','bad')}finally{if(button)button.disabled=false}}
  function init(){addStyle();addNav();shell();document.getElementById('weeklyFinanceRefresh')?.addEventListener('click',()=>void load());document.getElementById('connectionSelect')?.addEventListener('change',()=>queueMicrotask(()=>void load()));if(connectionId())queueMicrotask(()=>void load())}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
