import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { join } from 'node:path';

const root=process.cwd();
const read=(path)=>readFile(join(root,path),'utf8');
const foundationalMigrations=[
 'supabase/migrations/20260813155705_marketplace_v4_metadata.sql',
 'supabase/migrations/20260813162709_marketplace_v4_analytics_core.sql',
 'supabase/migrations/20260813163144_marketplace_v4_sync_locking.sql',
 'supabase/migrations/20260813164133_marketplace_v4_ownership_integrity.sql',
 'supabase/migrations/20260813183139_marketplace_sync_db_reconciliation_guard.sql',
 'supabase/migrations/20260813183453_product_cost_no_overlap.sql',
 'supabase/migrations/20260813183547_replace_cost_overlap_extension_with_trigger.sql'
];
const liveSignalMigration='supabase/migrations/20260816180000_add_live_order_signal_layer.sql';
const operatingExpenseMigration='supabase/migrations/20260816183000_add_operating_expense_ledger.sql';
const hardeningMigration='supabase/migrations/20260816203000_harden_browser_privileges_and_fk_indexes.sql';
const edgeFunctions=['connection-health','dashboard-summary','marketplace-connections','product-costs','product-costs-bulk','risk-alerts','sync-history','trendyol-cargo-sync','trendyol-credentials','trendyol-otherfinancials-sync','trendyol-sync','v4-auth','v4-beta','webhook-manager','order-events','live-overview','decision-center','operating-expenses','portfolio-summary'];

test('foundational and vNext migrations are version controlled',async()=>{for(const migration of foundationalMigrations)await access(join(root,migration));for(const migration of [liveSignalMigration,operatingExpenseMigration,hardeningMigration])await access(join(root,migration))});

test('core financial tables are created with RLS and owner policies',async()=>{const metadata=await read(foundationalMigrations[0]),analytics=await read(foundationalMigrations[1]);for(const table of ['marketplace_connections','marketplace_sync_runs']){assert.match(metadata,new RegExp(`create table public\\.${table}\\b`,'i'));assert.match(metadata,new RegExp(`alter table public\\.${table} enable row level security`,'i'));assert.match(metadata,new RegExp(`${table}_select_own`,'i'))}for(const table of ['marketplace_daily_financials','marketplace_product_daily_metrics','marketplace_product_costs']){assert.match(analytics,new RegExp(`create table public\\.${table}\\b`,'i'));assert.match(analytics,new RegExp(`alter table public\\.${table} enable row level security`,'i'));assert.match(analytics,new RegExp(`${table}_select_own`,'i'))}for(const sql of [metadata,analytics]){assert.match(sql,/using \(\(select auth\.uid\(\)\) = user_id\)/i);assert.match(sql,/revoke all on table/i);assert.match(sql,/grant select on table/i)}});

test('live order signal and operating expense tables are owner isolated and browser read-only',async()=>{const live=await read(liveSignalMigration),expenses=await read(operatingExpenseMigration);for(const table of ['marketplace_webhooks','marketplace_order_events','marketplace_live_orders']){assert.match(live,new RegExp(`create table if not exists public\\.${table}\\b`,'i'));assert.match(live,new RegExp(`alter table public\\.${table} enable row level security`,'i'));assert.match(live,new RegExp(`${table}_select_own`,'i'));assert.match(live,new RegExp(`revoke all on table public\\.${table} from anon, authenticated`,'i'));assert.match(live,new RegExp(`grant select on table public\\.${table} to authenticated`,'i'))}assert.match(expenses,/create table if not exists public\.marketplace_operating_expenses/i);assert.match(expenses,/marketplace_operating_expenses_connection_owner_fkey/i);assert.match(expenses,/alter table public\.marketplace_operating_expenses enable row level security/i);assert.match(expenses,/revoke all on table public\.marketplace_operating_expenses from anon, authenticated/i);assert.match(expenses,/grant select on table public\.marketplace_operating_expenses to authenticated/i)});

test('browser grants for sync artifacts are explicitly tightened and owner FKs are indexed',async()=>{const sql=await read(hardeningMigration);for(const table of ['marketplace_cargo_invoice_items','marketplace_order_product_map','marketplace_product_cargo_allocations']){assert.match(sql,new RegExp(`revoke all on table public\\.${table} from anon, authenticated`,'i'));assert.match(sql,new RegExp(`grant select on table public\\.${table} to authenticated`,'i'))}for(const index of ['marketplace_webhooks_connection_owner_idx','marketplace_order_events_connection_owner_idx','marketplace_live_orders_connection_owner_idx','marketplace_operating_expenses_connection_owner_idx'])assert.match(sql,new RegExp(index));assert.doesNotMatch(sql,/alter default privileges/i)});

test('ownership integrity and database guards are reproducible',async()=>{const ownership=await read(foundationalMigrations[3]),reconciliation=await read(foundationalMigrations[4]),overlap=await read(foundationalMigrations[6]);assert.match(ownership,/unique \(id, user_id\)/i);for(const table of ['marketplace_sync_runs','marketplace_daily_financials','marketplace_product_daily_metrics','marketplace_product_costs'])assert.match(ownership,new RegExp(`${table}_connection_owner_fkey`,'i'));assert.match(reconciliation,/SYNC_RECONCILIATION_FAILED/);assert.match(reconciliation,/trg_marketplace_sync_reconciliation/);assert.match(overlap,/PRODUCT_COST_PERIOD_OVERLAP/)});

test('all deployed Edge Function sources and the shared finance core are present',async()=>{for(const name of edgeFunctions)await access(join(root,'supabase','functions',name,'index.ts'));await access(join(root,'supabase','functions','_shared','finance.js'));assert.equal(edgeFunctions.length,19)});

test('external order callback uses independent authentication and provider reconciliation',async()=>{const receiver=await read('supabase/functions/order-events/index.ts'),manager=await read('supabase/functions/webhook-manager/index.ts'),config=await read('supabase/config.toml');assert.match(receiver,/x-api-key/i);assert.match(receiver,/SHA-256/i);assert.match(receiver,/secret_hash/);assert.match(receiver,/event_fingerprint/);assert.match(receiver,/on conflict \(event_fingerprint\) do nothing/i);assert.doesNotMatch(receiver,/customerFirstName|customerLastName|shipmentAddress|invoiceAddress|phone/i);assert.match(manager,/authenticationType:'API_KEY'/);assert.match(manager,/subscribedStatuses:\[\]/);assert.match(manager,/providerVerified/);assert.match(manager,/method:'PUT'/);assert.match(manager,/\/activate/);assert.match(manager,/providerStatus/);assert.doesNotMatch(manager,/alreadyActive:true/);assert.match(config,/\[functions\.order-events\][\s\S]*?verify_jwt = false/);assert.match(config,/\[functions\.webhook-manager\][\s\S]*?verify_jwt = true/)});

test('large financial reads use the shared paging guard instead of endpoint-local copies',async()=>{const shared=await read('supabase/functions/_shared/finance.js');assert.match(shared,/PAGE_SIZE = 1000/);assert.match(shared,/MAX_ROWS = 100000/);assert.match(shared,/DATA_TOO_LARGE/);for(const name of ['dashboard-summary','decision-center','risk-alerts','portfolio-summary']){const source=await read(`supabase/functions/${name}/index.ts`);assert.match(source,/readAllPages/);assert.match(source,/\.\.\/_shared\/finance\.js/);assert.doesNotMatch(source,/async function paged\(/)}const expenses=await read('supabase/functions/operating-expenses/index.ts');assert.match(expenses,/MAX_LEDGER=5000/);assert.match(expenses,/EXPENSE_LEDGER_TOO_LARGE/)});

test('financial confidence is explainable and excludes non-applicable evidence',async()=>{const source=await read('supabase/functions/decision-center/index.ts'),ui=await read('vnext.js');for(const signal of ['salesEvidence','returnEvidence','costCoverage','cargoCoverage','classification','freshness'])assert.match(source,new RegExp(signal));assert.match(source,/evidence_confidence_v3_shared_finance/);assert.match(source,/applicable/);assert.match(source,/activeComponents/);assert.match(source,/moneyLeakRadar/);assert.match(ui,/Finansal veri güveni/);assert.match(ui,/Bu dönemde ölçülmedi/);assert.match(ui,/Temel ağırlık/)});

test('portfolio contribution uses the shared completeness guard and stays unknown when cost is incomplete',async()=>{const portfolio=await read('supabase/functions/portfolio-summary/index.ts'),shared=await read('supabase/functions/_shared/finance.js'),ui=await read('vnext.js');assert.match(portfolio,/contributionAfterKnownCosts/);assert.match(portfolio,/salesCostCoverage/);assert.match(shared,/costCoverage/);assert.match(shared,/return null/);assert.match(portfolio,/knownCashAfterFeesAndStoppage/);assert.match(portfolio,/muhasebe net kârı değildir/i);assert.match(ui,/Maliyet \+ gider sonrası katkı/);assert.match(ui,/Bilinmiyor/)});

test('Trendyol sync preserves audit visibility for unclassified adjustments',async()=>{const sync=await read('supabase/functions/trendyol-sync/index.ts'),alerts=await read('v4-alerts.js');assert.match(sync,/unclassifiedAdjustmentRows/);assert.match(alerts,/sınıflandırılamadı/)});

test('seller dashboard uses one consolidated vNext behavior layer',async()=>{const loader=await read('v4-alerts.js'),next=await read('vnext.js'),css=await read('vnext.css'),opsCss=await read('vnext-ops.css');assert.match(loader,/\/vnext\.css/);assert.match(loader,/\/vnext\.js/);assert.match(loader,/\/vnext-ops\.css/);assert.doesNotMatch(loader,/vnext-ops\.js/);assert.match(next,/Hızlı sipariş sinyali, sonradan doğrulanan finans gerçeği/);assert.match(next,/Canlı Siparişler/);assert.match(next,/İşletme Giderleri/);assert.match(next,/Mağaza Portföyü/);assert.match(next,/kkRefreshAuxiliary/);assert.match(css,/--kk-copper:#f2a65a/);assert.match(css,/--kk-ice:#79c7ff/);assert.match(opsCss,/\.kk-ops-grid/);await assert.rejects(access(join(root,'vnext-ops.js')))});

test('public browser code does not contain privileged Supabase secrets',async()=>{const browserFiles=['app-core.js','app-data.js','app-bulk.js','demo.js','v4.js','v4-security.js','v4-enhance.js','v4-alerts.js','vnext.js'],forbidden=[/SUPABASE_SERVICE_ROLE_KEY/,/service_role/i,/SUPABASE_DB_URL/,/api_secret\s*[:=]\s*['"][^'"]+/i];for(const file of browserFiles){const source=await read(file);for(const pattern of forbidden)assert.doesNotMatch(source,pattern,`${file} contains a privileged secret marker`)}});

test('canonical seller route hides historical implementation filename',async()=>{const vercel=await read('vercel.json');assert.match(vercel,/"source"\s*:\s*"\/uygulama"/);assert.match(vercel,/"destination"\s*:\s*"\/v4\.html"/);assert.match(vercel,/"source"\s*:\s*"\/v4\.html"/);assert.match(vercel,/"destination"\s*:\s*"\/uygulama"/)});
