import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { join } from 'node:path';

const root=process.cwd();
const read=(path)=>readFile(join(root,path),'utf8');
const foundationalMigrations=[
 'supabase/migrations/20260813155705_marketplace_v4_metadata.sql',
 'supabase/migrations/20260813162709_marketplace_v4_analytics_core.sql',
 'supabase/migrations/20260813163144_marketplace_v4_sync_locking.sql',
 'supabase/migrations/20260813164133_marketplace_v4_ownership_integrity.sql',
 'supabase/migrations/20260813183139_marketplace_sync_db_reconciliation_guard.sql',
 'supabase/migrations/20260813183453_product_cost_no_overlap.sql',
 'supabase/migrations/20260813183547_replace_cost_overlap_extension_with_trigger.sql'
];
const liveSignalMigration='supabase/migrations/20260816180000_add_live_order_signal_layer.sql';
const operatingExpenseMigration='supabase/migrations/20260816183000_add_operating_expense_ledger.sql';
const hardeningMigration='supabase/migrations/20260816203000_harden_browser_privileges_and_fk_indexes.sql';
const saleReadyMigration='supabase/migrations/20260818180000_sale_ready_marketplaces_and_billing.sql';
const hepsiburadaMigration='supabase/migrations/20260818213000_hepsiburada_finance_provenance.sql';
const n11Migration='supabase/migrations/20260818233000_n11_order_finance_provenance.sql';
const amazonMigration='supabase/migrations/20260819003000_amazon_spapi_oauth_and_finance.sql';
const edgeFunctions=['connection-health','dashboard-summary','marketplace-connections','marketplace-credentials','marketplace-import','product-costs','product-costs-bulk','risk-alerts','sync-history','trendyol-cargo-sync','trendyol-credentials','trendyol-otherfinancials-sync','trendyol-sync','hepsiburada-sync','n11-sync','amazon-auth-start','amazon-auth-login','amazon-auth-callback','amazon-sync','v4-auth','v4-beta','webhook-manager','order-events','live-overview','decision-center','operating-expenses','portfolio-summary','billing-summary','billing-checkout','billing-portal','billing-webhook'];

test('foundational and vNext migrations are version controlled',async()=>{for(const migration of foundationalMigrations)await access(join(root,migration));for(const migration of [liveSignalMigration,operatingExpenseMigration,hardeningMigration,saleReadyMigration,hepsiburadaMigration,n11Migration,amazonMigration,'supabase/migrations/20260818170055_security_hardening.sql'])await access(join(root,migration))});

test('core financial tables are created with RLS and owner policies',async()=>{const metadata=await read(foundationalMigrations[0]),analytics=await read(foundationalMigrations[1]);for(const table of ['marketplace_connections','marketplace_sync_runs']){assert.match(metadata,new RegExp(`create table public\\.${table}\\b`,'i'));assert.match(metadata,new RegExp(`alter table public\\.${table} enable row level security`,'i'));assert.match(metadata,new RegExp(`${table}_select_own`,'i'))}for(const table of ['marketplace_daily_financials','marketplace_product_daily_metrics','marketplace_product_costs']){assert.match(analytics,new RegExp(`create table public\\.${table}\\b`,'i'));assert.match(analytics,new RegExp(`alter table public\\.${table} enable row level security`,'i'));assert.match(analytics,new RegExp(`${table}_select_own`,'i'))}for(const sql of [metadata,analytics]){assert.match(sql,/using \(\(select auth\.uid\(\)\) = user_id\)/i);assert.match(sql,/revoke all on table/i);assert.match(sql,/grant select on table/i)}});

test('live order signal and operating expense tables are owner isolated and browser read-only',async()=>{const live=await read(liveSignalMigration),expenses=await read(operatingExpenseMigration);for(const table of ['marketplace_webhooks','marketplace_order_events','marketplace_live_orders']){assert.match(live,new RegExp(`create table if not exists public\\.${table}\\b`,'i'));assert.match(live,new RegExp(`alter table public\\.${table} enable row level security`,'i'));assert.match(live,new RegExp(`${table}_select_own`,'i'));assert.match(live,new RegExp(`revoke all on table public\\.${table} from anon, authenticated`,'i'));assert.match(live,new RegExp(`grant select on table public\\.${table} to authenticated`,'i'))}assert.match(expenses,/create table if not exists public\.marketplace_operating_expenses/i);assert.match(expenses,/marketplace_operating_expenses_connection_owner_fkey/i);assert.match(expenses,/alter table public\.marketplace_operating_expenses enable row level security/i);assert.match(expenses,/revoke all on table public\.marketplace_operating_expenses from anon, authenticated/i);assert.match(expenses,/grant select on table public\.marketplace_operating_expenses to authenticated/i)});

test('browser grants for sync artifacts are explicitly tightened and owner FKs are indexed',async()=>{const sql=await read(hardeningMigration);for(const table of ['marketplace_cargo_invoice_items','marketplace_order_product_map','marketplace_product_cargo_allocations']){assert.match(sql,new RegExp(`revoke all on table public\\.${table} from anon, authenticated`,'i'));assert.match(sql,new RegExp(`grant select on table public\\.${table} to authenticated`,'i'))}for(const index of ['marketplace_webhooks_connection_owner_idx','marketplace_order_events_connection_owner_idx','marketplace_live_orders_connection_owner_idx','marketplace_operating_expenses_connection_owner_idx'])assert.match(sql,new RegExp(index));assert.doesNotMatch(sql,/alter default privileges/i)});

test('ownership integrity and database guards are reproducible',async()=>{const ownership=await read(foundationalMigrations[3]),reconciliation=await read(foundationalMigrations[4]),overlap=await read(foundationalMigrations[6]);assert.match(ownership,/unique \(id, user_id\)/i);for(const table of ['marketplace_sync_runs','marketplace_daily_financials','marketplace_product_daily_metrics','marketplace_product_costs'])assert.match(ownership,new RegExp(`${table}_connection_owner_fkey`,'i'));assert.match(reconciliation,/SYNC_RECONCILIATION_FAILED/);assert.match(reconciliation,/trg_marketplace_sync_reconciliation/);assert.match(overlap,/PRODUCT_COST_PERIOD_OVERLAP/)});

test('all deployed Edge Function sources and shared runtime cores are present',async()=>{for(const name of edgeFunctions)await access(join(root,'supabase','functions',name,'index.ts'));for(const file of ['finance.js','postgres.ts','observability.ts','billing.ts','edge-auth.ts','providers.ts','request-security.ts'])await access(join(root,'supabase','functions','_shared',file));assert.equal(edgeFunctions.length,31)});

test('external order callback uses independent authentication and provider reconciliation',async()=>{const receiver=await read('supabase/functions/order-events/index.ts'),manager=await read('supabase/functions/webhook-manager/index.ts'),config=await read('supabase/config.toml');assert.match(receiver,/x-api-key/i);assert.match(receiver,/SHA-256/i);assert.match(receiver,/secret_hash/);assert.match(receiver,/event_fingerprint/);assert.match(receiver,/on conflict \(event_fingerprint\) do nothing/i);assert.doesNotMatch(receiver,/customerFirstName|customerLastName|shipmentAddress|invoiceAddress|phone/i);assert.match(manager,/authenticationType:'API_KEY'/);assert.match(manager,/subscribedStatuses:\[\]/);assert.match(manager,/providerVerified/);assert.match(manager,/method:'PUT'/);assert.match(manager,/\/activate/);assert.match(manager,/providerStatus/);assert.doesNotMatch(manager,/alreadyActive:true/);assert.match(config,/\[functions\.order-events\][\s\S]*?verify_jwt = false/);assert.match(config,/\[functions\.webhook-manager\][\s\S]*?verify_jwt = true/)});

test('database-backed Edge Functions require the custom transaction-pooler secret',async()=>{const shared=await read('supabase/functions/_shared/postgres.ts');assert.match(shared,/port!==?'6543'|url\.port!=='6543'/);assert.match(shared,/TRANSACTION_POOLER_REQUIRED/);assert.match(shared,/prepare:false/);assert.match(shared,/max:1/);const dbFunctions=['operating-expenses','order-events','product-costs-bulk','trendyol-cargo-sync','trendyol-credentials','trendyol-otherfinancials-sync','trendyol-sync','hepsiburada-sync','n11-sync','amazon-auth-start','amazon-auth-login','amazon-auth-callback','amazon-sync','webhook-manager','marketplace-credentials','marketplace-import'];for(const name of dbFunctions){const source=await read(`supabase/functions/${name}/index.ts`);assert.match(source,/Deno\.env\.get\(["']KARKALKAN_DB_POOLER_URL["']\)/);assert.match(source,/createTransactionPool/);assert.doesNotMatch(source,/Deno\.env\.get\(["']SUPABASE_DB_URL["']\)/);assert.doesNotMatch(source,/import postgres from/)}});

test('sale-ready provider and billing state is tenant-safe and payment details stay outside the database',async()=>{const migration=await read(saleReadyMigration),providers=await read('supabase/functions/_shared/providers.ts'),webhook=await read('supabase/functions/billing-webhook/index.ts'),config=await read('supabase/config.toml');for(const provider of ['trendyol','hepsiburada','n11','amazon','flo'])assert.match(providers,new RegExp(`${provider}:`));for(const table of ['billing_customers','billing_subscriptions','billing_events']){assert.match(migration,new RegExp(`create table public\\.${table}`,'i'));assert.match(migration,new RegExp(`alter table public\\.${table} enable row level security`,'i'));assert.match(migration,new RegExp(`revoke all on table public\\.${table} from anon, authenticated`,'i'))}assert.doesNotMatch(migration,/card_number|cvv|payment_method_details/i);assert.match(webhook,/Paddle-Signature/);assert.match(webhook,/timingSafeHexEqual/);assert.match(webhook,/payload_sha256/);assert.match(config,/\[functions\.billing-webhook\][\s\S]*?verify_jwt = false/)});

test('FLO partner handoff is Vault-backed and Paddle checkout fails closed on partial configuration',async()=>{const providers=await read('supabase/functions/_shared/providers.ts'),connections=await read('supabase/functions/marketplace-connections/index.ts'),credentials=await read('supabase/functions/marketplace-credentials/index.ts'),billing=await read('supabase/functions/_shared/billing.ts'),checkout=await read('supabase/functions/billing-checkout/index.ts'),webhook=await read('supabase/functions/billing-webhook/index.ts'),env=await read('.env.example');assert.match(providers,/flo:\{label:'FLO'.*mode:'file'.*tier:'gated'.*sellerIdRequired:true.*api_username.*api_password/);assert.match(connections,/INVALID_FLO_SELLER_ID/);assert.match(credentials,/connection\.marketplace==='flo'\?'pending':'connected'/);assert.match(credentials,/vault\.(update_secret|create_secret)/);assert.match(billing,/function paddleReadiness/);assert.match(billing,/PADDLE_PRICE_ID/);assert.match(checkout,/!readiness\.ready/);assert.match(webhook,/config\.webhookToleranceSeconds/);assert.match(env,/PADDLE_WEBHOOK_TOLERANCE_SECONDS=5/)});

test('normalized marketplace import is bounded, owner-scoped and financially conservative',async()=>{const source=await read('supabase/functions/marketplace-import/index.ts');assert.match(source,/MAX_ROWS=5000/);assert.match(source,/user_id=\$\{user\.id\}/);assert.match(source,/known_cogs:known/);assert.match(source,/profit_confidence:known===null\?'platform_only':'cost_known'/);assert.match(source,/normalized_csv/);assert.doesNotMatch(source,/service_role|SUPABASE_DB_URL/i)});

test('callback hash comparison is timing safe and critical failures are externally monitorable',async()=>{const receiver=await read('supabase/functions/order-events/index.ts'),sync=await read('supabase/functions/trendyol-sync/index.ts'),hepsiburada=await read('supabase/functions/hepsiburada-sync/index.ts'),n11=await read('supabase/functions/n11-sync/index.ts'),monitoring=await read('supabase/functions/_shared/observability.ts');assert.match(receiver,/timingSafeEqualSha256/);assert.match(receiver,/diff\|=/);assert.doesNotMatch(receiver,/String\(hook\.secret_hash\)!==suppliedHash/);assert.match(monitoring,/npm:@sentry\/deno@10\.70\.0/);assert.match(monitoring,/SENTRY_DSN/);assert.match(monitoring,/sendDefaultPii:false/);assert.match(sync,/captureSafeFailure\(["']trendyol-sync["'],\s*code,\s*cause\)/);assert.match(hepsiburada,/captureSafeFailure\('hepsiburada-sync',code,cause\)/);assert.match(n11,/captureSafeFailure\('n11-sync',code,cause\)/)});

test('Hepsiburada sync uses the official finance contract without persisting customer PII',async()=>{const sync=await read('supabase/functions/hepsiburada-sync/index.ts'),providers=await read('supabase/functions/_shared/providers.ts'),connections=await read('supabase/functions/marketplace-connections/index.ts'),migration=await read(hepsiburadaMigration),config=await read('supabase/config.toml'),ui=await read('v4.js');assert.match(sync,/https:\/\/mpfinance-external\.hepsiburada\.com/);assert.match(sync,/\/transactions\/merchantid\//);assert.match(sync,/\/orders\/merchantid\//);assert.match(sync,/RecordDateStart/);assert.match(sync,/OrderDateStart/);assert.match(sync,/Authorization:authHeader/);assert.match(sync,/'User-Agent':userAgent/);assert.match(sync,/PAGE_SIZE=100/);assert.match(sync,/HEPSIBURADA_CURRENCY_CONFLICT/);assert.match(sync,/hepsiburada_finance_v1/);assert.doesNotMatch(sync,/customerName|customerId|shipmentAddress|invoiceAddress|phone|email/i);assert.match(providers,/label:'Servis anahtarı'/);assert.match(connections,/INVALID_HEPSIBURADA_MERCHANT_ID/);assert.match(migration,/hepsiburada_finance_v1/);assert.match(config,/\[functions\.hepsiburada-sync\][\s\S]*?verify_jwt = true/);assert.match(ui,/hepsiburada-sync/)});

test('n11 sync uses official order and return contracts and deliberately excludes customer PII',async()=>{const sync=await read('supabase/functions/n11-sync/index.ts'),providers=await read('supabase/functions/_shared/providers.ts'),migration=await read(n11Migration),config=await read('supabase/config.toml'),ui=await read('v4.js');assert.match(sync,/https:\/\/api\.n11\.com\/rest\/delivery\/v1\/shipmentPackages/);assert.match(sync,/https:\/\/api\.n11\.com\/ws\/ReturnService/);assert.match(sync,/headers:\{appkey:appKey,appsecret:appSecret/);assert.match(sync,/ClaimReturnListRequest/);assert.match(sync,/commissionRate/);assert.match(sync,/netMarketingFeeRate/);assert.match(sync,/n11_order_api_estimate_v1/);assert.match(sync,/cargo_and_statement_adjustments_require_n11_payment_detail_report/);assert.doesNotMatch(sync,/billingAddress|shippingAddress|customerEmail|customerfullName|customerId|tcIdentityNumber|buyerPhone|buyerEmail|buyerName/i);assert.match(providers,/n11:\{label:'n11'.*tier:'ready'/);assert.match(migration,/n11_order_api_estimate_v1/);assert.match(config,/\[functions\.n11-sync\][\s\S]*?verify_jwt = true/);assert.match(ui,/n11-sync/)});

test('Amazon SP-API OAuth and Finances integration is state-bound, Vault-backed and PII-minimal',async()=>{const start=await read('supabase/functions/amazon-auth-start/index.ts'),login=await read('supabase/functions/amazon-auth-login/index.ts'),callback=await read('supabase/functions/amazon-auth-callback/index.ts'),sync=await read('supabase/functions/amazon-sync/index.ts'),migration=await read(amazonMigration),providers=await read('supabase/functions/_shared/providers.ts'),config=await read('supabase/config.toml'),ui=await read('v4.js');assert.match(start,/sellercentral\.amazon\.com\.tr/);assert.match(start,/crypto\.getRandomValues/);assert.match(start,/SHA-256/);assert.match(start,/amazon_oauth_states/);assert.match(login,/amazon_callback_uri/);assert.match(login,/AMAZON_CALLBACK_HOSTS/);assert.match(login,/redirect_uri/);assert.match(login,/amazon_oauth_states/);assert.match(callback,/api\.amazon\.com\/auth\/o2\/token/);assert.match(callback,/consumed_at=now\(\)/);assert.match(callback,/vault\.(update_secret|create_secret)/);assert.match(callback,/kk\.amazon\.\$\{connectionId\}\.refresh_token/);assert.match(sync,/sellingpartnerapi-eu\.amazon\.com/);assert.match(sync,/\/finances\/2024-06-19\/transactions/);assert.match(sync,/A33AVAJ2PDY3EV/);assert.match(sync,/x-amz-access-token/);assert.match(sync,/PAGE_PACING_MS=2_050/);assert.match(sync,/financial_events_can_lag_up_to_48_hours/);assert.match(sync,/captureSafeFailure\('amazon-sync',code,cause\)/);assert.doesNotMatch(sync,/buyerEmail|buyerName|shippingAddress|billingAddress|phone|customerName/i);assert.match(migration,/create table public\.amazon_oauth_states/i);assert.match(migration,/revoke all on table public\.amazon_oauth_states from anon, authenticated/i);assert.match(migration,/amazon_finances_2024_06_19/);assert.match(providers,/amazon:\{label:'Amazon'.*mode:'oauth'.*tier:'gated'/);assert.match(config,/\[functions\.amazon-auth-start\][\s\S]*?verify_jwt = true/);assert.match(config,/\[functions\.amazon-auth-login\][\s\S]*?verify_jwt = true/);assert.match(config,/\[functions\.amazon-auth-callback\][\s\S]*?verify_jwt = false/);assert.match(config,/\[functions\.amazon-sync\][\s\S]*?verify_jwt = true/);assert.match(ui,/amazon-auth-start/);assert.match(ui,/amazon-auth-login/);assert.match(ui,/amazon-sync/)});

test('large-store continuation boundary is explicit and not disguised by a larger page limit',async()=>{const limits=await read('KNOWN_LIMITATIONS.md');assert.match(limits,/409 SYNC_TOO_LARGE/);assert.match(limits,/continuation cursor/i);assert.match(limits,/idempotent page writes/i);assert.match(limits,/intentionally documented, not implemented yet/i)});

test('large financial reads use the shared paging guard instead of endpoint-local copies',async()=>{const shared=await read('supabase/functions/_shared/finance.js');assert.match(shared,/PAGE_SIZE = 1000/);assert.match(shared,/MAX_ROWS = 100000/);assert.match(shared,/DATA_TOO_LARGE/);for(const name of ['dashboard-summary','decision-center','risk-alerts','portfolio-summary']){const source=await read(`supabase/functions/${name}/index.ts`);assert.match(source,/readAllPages/);assert.match(source,/\.\.\/_shared\/finance\.js/);assert.doesNotMatch(source,/async function paged\(/)}const expenses=await read('supabase/functions/operating-expenses/index.ts');assert.match(expenses,/MAX_LEDGER=5000/);assert.match(expenses,/EXPENSE_LEDGER_TOO_LARGE/)});

test('financial confidence is explainable and excludes non-applicable evidence',async()=>{const source=await read('supabase/functions/decision-center/index.ts'),ui=await read('vnext.js');for(const signal of ['salesEvidence','returnEvidence','costCoverage','cargoCoverage','classification','freshness'])assert.match(source,new RegExp(signal));assert.match(source,/evidence_confidence_v3_shared_finance/);assert.match(source,/applicable/);assert.match(source,/activeComponents/);assert.match(source,/moneyLeakRadar/);assert.match(ui,/Finansal veri güveni/);assert.match(ui,/Bu dönemde ölçülmedi/);assert.match(ui,/Temel ağırlık/)});

test('portfolio contribution uses the shared completeness guard and stays unknown when cost is incomplete',async()=>{const portfolio=await read('supabase/functions/portfolio-summary/index.ts'),shared=await read('supabase/functions/_shared/finance.js'),ui=await read('vnext.js');assert.match(portfolio,/contributionAfterKnownCosts/);assert.match(portfolio,/salesCostCoverage/);assert.match(shared,/costCoverage/);assert.match(shared,/return null/);assert.match(portfolio,/knownCashAfterFeesAndStoppage/);assert.match(portfolio,/muhasebe net kârı değildir/i);assert.match(ui,/Maliyet \+ gider sonrası katkı/);assert.match(ui,/Bilinmiyor/)});

test('Trendyol sync preserves audit visibility for unclassified adjustments',async()=>{const sync=await read('supabase/functions/trendyol-sync/index.ts'),alerts=await read('v4-alerts.js');assert.match(sync,/unclassifiedAdjustmentRows/);assert.match(alerts,/sınıflandırılamadı/)});

test('seller dashboard uses one consolidated vNext behavior layer',async()=>{const loader=await read('v4-alerts.js'),next=await read('vnext.js'),css=await read('vnext.css'),opsCss=await read('vnext-ops.css');assert.match(loader,/\/vnext\.css/);assert.match(loader,/\/vnext\.js/);assert.match(loader,/\/vnext-ops\.css/);assert.match(loader,/\/product-2026\.css/);assert.doesNotMatch(loader,/vnext-ops\.js/);assert.match(next,/Önce sonucu görün\. Kanıtı kontrol edin\. Aksiyonu uygulayın\./);assert.match(next,/Rakip izleme/);assert.match(next,/İşletme giderleri/);assert.match(next,/Mağaza portföyü/);assert.match(next,/kkRefreshAuxiliary/);assert.match(css,/--kk-copper:#f2a65a/);assert.match(css,/--kk-ice:#79c7ff/);assert.match(opsCss,/\.kk-ops-grid/);await assert.rejects(access(join(root,'vnext-ops.js')))});

test('public browser code does not contain privileged Supabase secrets',async()=>{const browserFiles=['app-core.js','app-data.js','app-bulk.js','demo.js','v4.js','v4-security.js','v4-enhance.js','v4-alerts.js','vnext.js','sale-ready.js'],forbidden=[/SUPABASE_SERVICE_ROLE_KEY/,/service_role/i,/SUPABASE_DB_URL/,/api_secret\s*[:=]\s*['"][^'"]+/i];for(const file of browserFiles){const source=await read(file);for(const pattern of forbidden)assert.doesNotMatch(source,pattern,`${file} contains a privileged secret marker`)}});

test('canonical seller route hides historical implementation filename',async()=>{const vercel=await read('vercel.json');assert.match(vercel,/"source"\s*:\s*"\/uygulama"/);assert.match(vercel,/"destination"\s*:\s*"\/v4\.html"/);assert.match(vercel,/"source"\s*:\s*"\/v4\.html"/);assert.match(vercel,/"destination"\s*:\s*"\/uygulama"/)});
